### PR TITLE
fix(macros): invoke handler stack overflow

### LINKED ISSUE #12488: [bug] [windows] invoking commands causes crash.
### Describe the bug

I have an application that exports many commands with structs as arguments. Unfortunately, on Windows machines, the application crashes after the first execution of the any command with the error:

```
thread 'main' has overflowed its stack
error: process didn't exit successfully: `target\debug\tauri-commands-crash.exe` (exit code: 0xc00000fd, STATUS_STACK_OVERFLOW)
```

The same code is working on OSX.

I prepared a repository that shows crash: https://github.com/singerxt/tauri-command-crash 

### Reproduction

1. On a Windows machine, pull repository https://github.com/singerxt/tauri-command-crash
2. `cd tauri-cmmand-crash && pnpm i`
3. Run application dev mode `pnpm tauri dev`
4. Fill in the visible input for the name and click the button
5. Notice crash.

### Expected behavior

The application will not crash. 

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.17763 x86_64 (X64)
    ✔ WebView2: 131.0.2903.146
    ✔ MSVC:
        - Visual Studio Build Tools 2022
        - Visual Studio Community 2022
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: 1.81-x86_64-pc-windows-msvc (default)
    - node: 20.15.1
    - pnpm: 9.6.0
    - npm: 10.7.0

[-] Packages
    - tauri �: 2.2.3
    - tauri-build �: 2.0.5
    - wry �: 0.48.1
    - tao �: 0.31.1
    - @tauri-apps/api : 2.2.0
    - @tauri-apps/cli : 2.2.5

[-] Plugins
    - tauri-plugin-opener �: 2.2.3
    - @tauri-apps/plugin-opener : 2.2.5

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

```text
Finished `dev` profile [unoptimized + debuginfo] target(s) in 1m 18s
     Running `target\debug\tauri-commands-crash.exe`

thread 'main' has overflowed its stack
error: process didn't exit successfully: `target\debug\tauri-commands-crash.exe` (exit code: 0xc00000fd, STATUS_STACK_OVERFLOW)
 ELIFECYCLE  Command failed with exit code 3221225725.
```

### Additional context

1. The issue will not happen if you delete the struct argument from commands.
2. The issue is not happening if you export less then 50 commands (even with struct in argument)
3.  The issue is not happening with release builds only debug is affected.

### PR DESCRIPTION
**Pull request by Legend-Master**
Fix #12488

This is a very similar bug as #9882, the debug build of rust seems unable to optimize the function stack size, and with a small stack size limit on Windows, it overflows, and in release build, the optimization kicks in and there're no problems

So this fix turns each macro into a closure in debug build so rust wouldn't allocate the memory all at once and crash

### CODE REVIEW

File: crates/tauri-macros/src/command/wrapper.rs [hunk 1]
```diff
@@ -280,18 +280,25 @@ pub fn wrapper(attributes: TokenStream, item: TokenStream) -> TokenStream {
...
-
-          #body
-      }};
+      // double braces because the item is expected to be a block expression
+      ($path:path, $invoke:ident) => {
+        // The IIFE here is for preventing stack overflow on Windows debug build,
+        // see https://github.com/tauri-apps/tauri/issues/12488
+        {
+          #[cfg_attr(not(debug_assertions), inline(always))]
+          move || {
```
Comment (lucasfernog) [inline crates/tauri-macros/src/command/wrapper.rs:289]: ohh so nice that Rust optimizes this for us on release ❤️ awesome idea

**Review by lucasfernog — APPROVED** [review]
