### PR TITLE
Expose event interface. fixes #2733

### LINKED ISSUE #2733: The event module is private despite being exposed in the public API
### **Describe the bug**
The event module is private, making it impossible to reference `Event` or `EventHandler`.

### **To Reproduce**
1. Try to import `tauri::event::{Event, EventHandler}`

### **Expected behavior**
The module is not private.

### **Platform and Versions (required):**

```
Operating System - Windows, version 10.0.19042 X64
Webview2 - 94.0.992.38

Node.js environment
  Node.js - 16.11.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.0.0
  yarn - 1.22.15

Rust environment
  rustc - 1.57.0-nightly
  cargo - 1.57.0-nightly

App directory structure
/.git
/.idea
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - Set automatically by Vue CLI plugin
  devPath - Set automatically by Vue CLI plugin
  framework - Vue.js (Vue CLI)
  bundler - Webpack
```

### **Additional context**
I would like to do this:
```rs
fn some_func(&self) {
    self.handle.listen_global("send-packet", listener);
}

fn listener(event: Event) {
    // ...
}
```

Unfortunately, there is no way for me to `use` the necessary type, so this is impossible.

In addition, it is impossible to store the result of `listen_global` to be `unlisten`ed later, since there's no way to reference `EventHandler` in a struct.

I wonder if it's a Rust bug that the API is even allowed to do this. It's essentially exposing a private type in the public API, which you can't do normally.

### PR DESCRIPTION
**Pull request by Chaostheorie**
Expose `tauri::event` and rename `tauri::event::Event` to `EmittedEvent`. Temporary fix for #2733. This is supposed to be a POC for my internal use until #2733 is resolved in v1.x.

### What kind of change does this PR introduce?

- [x] Bugfix
- [x] Refactor

### Does this PR introduce a breaking change?

- [x] Yes, and the changes aren't approved 
- [ ] No

> Note: Tests were passing on GNU/Linux 5.15.18-1-lts with rustc 1.58.0

### CODE REVIEW

File: core/tauri/src/lib.rs [hunk 1]
```diff
@@ -35,7 +35,7 @@ pub mod command;
 /// The Tauri API endpoints.
 mod endpoints;
 mod error;
-mod event;
+pub mod event;
```
Comment (amrbashir) [inline core/tauri/src/lib.rs]: don't export this whole mod. just do `pub use` for the types you need exported only like how it is done a few lines below.

File: core/tauri/src/event.rs [hunk 2]
```diff
@@ -23,12 +23,12 @@ impl fmt::Display for EventHandler {
 
 /// An event that was triggered.
 #[derive(Debug, Clone)]
-pub struct Event {
+pub struct EmittedEvent {
```
Comment (amrbashir) [inline core/tauri/src/event.rs]: This should stay `Event`

**Review by amrbashir — CHANGES_REQUESTED** [review]
Thanks for taking the time to fix this. 

You need to:
1. rename `EmittedEvent` to `Event` and remove any mention of `EmittedEvent`
2. rename `Event` to `RunEvent`, obviously this will clash with the `runtime::RunEvent` import in `core/tauri/src/app.rs` so you're just gonna need to rename the import and not the original struct, something like this `use runtime::RunEvent as RuntimeRunEvent`

File: core/tauri/src/lib.rs (hunk 1 above)
Comment (Chaostheorie) [reply core/tauri/src/lib.rs]: It seems that only Event and Eventhandler are needed directly.

File: core/tauri/src/app.rs [hunk 3]
```diff
@@ -16,7 +16,7 @@ use crate::{
     http::{Request as HttpRequest, Response as HttpResponse},
     webview::{WebviewAttributes, WindowBuilder},
     window::{PendingWindow, WindowEvent},
-    Dispatch, ExitRequestedEventAction, RunEvent, Runtime,
+    Dispatch, ExitRequestedEventAction, RunEvent as RunTimeEvent, Runtime,
```
Comment (amrbashir) [inline core/tauri/src/app.rs]:
```suggestion
    Dispatch, ExitRequestedEventAction, RunEvent as RuntimeRunEvent, Runtime,
```

File: core/tauri/src/lib.rs [hunk 4]
```diff
@@ -84,12 +81,14 @@ pub use {
 };
 pub use {
   self::app::WindowMenuEvent,
+  self::event::{Event, EventHandler},
```
Comment (amrbashir) [inline core/tauri/src/lib.rs:84]: I think only `Event` needs to be exported

**Review by amrbashir — CHANGES_REQUESTED** [review]
You also need to add a changefil in `.changes` folder and don't forget to mention the breaking change `Event` -> `RunEvent`

File: core/tauri/src/lib.rs (hunk 4 above)
Comment (FabianLars) [reply core/tauri/src/lib.rs:84]: No we need EventHandler so the user can unlisten to events.
Edit: To clarify: "so the user can unlisten to events **later**", currently they can only immediately after listening (cause they can't store the EventHandler anywhere)

Comment (amrbashir) [reply core/tauri/src/lib.rs:84]: Ah okay

**Comment by Chaostheorie** [comment]
What would be the appropriate level for this change? Semver would dictate to use major since the API is changed, but semver doesn't seem to be enforced for `next`.

**Comment by FabianLars** [comment]
It's not enforced because of the prelease stuff, so patch is fine, as this needs to land in v1 anyway (mainly because of the EventHandler fix)

**Comment by Chaostheorie** [comment]
There seems to be a change request pending, but I can't figure out, what it is referring to. 

@amrbashir your name appears in the UI, have I overlooked something?

**Comment by FabianLars** [comment]
@Chaostheorie Don't worry, that's just the UI not updating until he approves the PR. As far as i can see you got everything he requested so far 👍

File: .changes/api-change-events.md [hunk 5]
```diff
@@ -0,0 +1,6 @@
+---
+"tauri": patch
+---
+
+- `tauri::event::Event` and `tauri::event::EventHandler` are now exported as `tauri::Event` and `tauri::EventHandler`
+- **breaking**: The old `tauri::app::Event` has been renamed to `tauri::app::RunEvent` and is available as `tauri::RunEvent`
```
Comment (amrbashir) [inline .changes/api-change-events.md]:
```suggestion
* **Breaking change**: Renamed `tauri::Event`  to `tauri::RunEvent`
* Exported `tauri::Event` and `tauri::EventHandler` so you can define a function and pass it to `Window::listen`
```

**Review by amrbashir — APPROVED** [review]

**Review by FabianLars — APPROVED** [review]

**Comment by Chaostheorie** [comment]
@amrbashir and @FabianLars thank you for the great help and explanations.
