### PR TITLE
fix(core): disable tao's drag-n-drop based on `fileDropEnabled`, closes #4580

### LINKED ISSUE #4580: [bug] CoInitializeEx with different thread mode causes panic
### Describe the bug

When running `CoInitializeEx` with a different thread mode than the one used by tao (for ex : `COINIT_MULTITHREADED`), the application panics, 

### Reproduction

Just call `CoInitializeEx` with `COINIT_MULTITHREADED` before everything as mentioned in the docs : 
https://docs.rs/tao/latest/x86_64-pc-windows-msvc/tao/platform/windows/trait.WindowBuilderExtWindows.html#tymethod.with_drag_and_drop

Code example : 
```rust
fn main() {
  unsafe{
    match CoInitializeEx(std::ptr::null(), COINIT_MULTITHREADED){
      Err(e) => {
          println!("Couldn't CoInitializeEx: {}", e);
        }
        Ok(_) => println!("CoInitializeEx done"),
    };
  }
  tauri::Builder::default()
    .invoke_handler(tauri::generate_handler![get_directory,get_selected_files,say_hello])
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
```

### Expected behavior

_No response_

### Platform and versions

```shell
Windows 10
tauri = { version = "1.0.2", features = ["api-all"] }
```

### Stack trace

```shell
CoInitializeEx done
thread 'main' panicked at 'OleInitialize failed! Result was: `RPC_E_CHANGED_MODE`. Make sure other crates are not using multithreaded COM library on the same thread or disable drag and drop support.', C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\tao-0.12.1\src\platform_impl\windows\window.rs:100:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error Command failed with exit code 101.
```

### Additional context

Normally this should not happen if `fileDropEnabled` is set to false, so if I understood right, tao's function 
https://docs.rs/tao/latest/x86_64-pc-windows-msvc/tao/platform/windows/trait.WindowBuilderExtWindows.html#tymethod.with_drag_and_drop 
Should take into consideration the given `fileDropEnabled` value.

### PR DESCRIPTION
**Pull request by amrbashir**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Review by lucasfernog — DISMISSED** [review]
Totally missed this, thanks!

File: core/tauri-runtime-wry/src/lib.rs [hunk 1]
```diff
@@ -2844,6 +2844,12 @@ fn create_webview<T: UserEvent>(
   {
     window_builder.inner = window_builder.inner.with_fullsize_content_view(true);
   }
+  #[cfg(target_os = "windows")]
```
Comment (lucasfernog) [inline core/tauri-runtime-wry/src/lib.rs]:
```suggestion
  #[cfg(windows)]
```

**Review by lucasfernog — APPROVED** [review]
