### PR TITLE
fix(tauri-runtime-wry): ensure tray is created when event loop ready

### LINKED ISSUE #9480: [bug] Second "ghost" menu bar icon on Sonoma
### Describe the bug

After upgrading to Sonoma 14.4.1, my menu bar app started showing a strange second icon near the apple icon.  It only happens on an external monitor with mirroring enabled.

Screenshot 2024-04-16 at 1 10 50 PM

### Reproduction

NOTE: this only repros sporadically.  See comment below for details.

- Run MacOS Sonoma 14.4.1
- Plug-in an external monitor (27")
- Enable mirroring
- Create two virtual desktops
- `yarn create tauri-app`
- Update `main.rs` with the code below
- Run the app via either via `yarn tauri dev` or `yarn tauri build` and install the application from the DMG

```
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use tauri::SystemTray;

use tauri::{CustomMenuItem, SystemTrayMenu, SystemTrayMenuItem};

fn main() {

    let quit = CustomMenuItem::new("quit".to_string(), "Quit");
    let hide = CustomMenuItem::new("hide".to_string(), "Hide");
    let tray_menu = SystemTrayMenu::new()
      .add_item(quit)
      .add_native_item(SystemTrayMenuItem::Separator)
      .add_item(hide);


    let system_tray = SystemTray::new()
      .with_menu(tray_menu);

    tauri::Builder::default()
      .system_tray(system_tray)
      .run(tauri::generate_context!())
      .expect("error while running tauri application");

}
```

Screenshot 2024-04-16 at 1 38 58 PM

### Expected behavior

 No ghost icon as shown in the screenshot

### Full `tauri info` output

```text
yarn run v1.22.19
$ tauri info

[✔] Environment
    - OS: Mac OS 14.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 18.16.0
    - pnpm: 8.8.0
    - yarn: 1.22.19
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 1.5.4
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.11

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
✨  Done in 3.36s.
```

### Stack trace

```text
N/A
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lucasfernog**
closes #9480

see https://github.com/tauri-apps/tray-icon/pull/122

this PR is kinda dangerous, reviewing this CRAZY workaround might make you never want to open github again

### CODE REVIEW

File: core/tauri-runtime-wry/src/lib.rs [hunk 1]
```diff
@@ -2129,34 +2143,48 @@ impl<T: UserEvent> Runtime<T> for Wry<T> {
   }
 
   #[cfg(all(desktop, feature = "system-tray"))]
-  fn system_tray(&self, mut system_tray: SystemTray) -> Result<Self::TrayHandler> {
+  fn system_tray(&self, system_tray: SystemTray) -> Result<Self::TrayHandler> {
```
Comment (amrbashir) [inline core/tauri-runtime-wry/src/lib.rs:2146]: I don't quite remember but I am assuming this function is only called for system tray defined on the `tauri::Builder`, right?

**Review by amrbashir — DISMISSED** [review]

File: core/tauri-runtime-wry/src/lib.rs (hunk 1 above)
Comment (lucasfernog) [reply core/tauri-runtime-wry/src/lib.rs:2146]: yeah, or system trays created in the setup hook...

**Review by amrbashir — APPROVED** [review]
