### PR TITLE
fix(core): properly emit events with object payload, closes #5482

### LINKED ISSUE #5482: [bug] Event payload sent between frontends does not get parsed into an object
### Describe the bug

I have two Tauri windows communicating with each other via events on the frontend. I would like to send an object from one window to another. From my understanding, the serialized JSON should be parsed automatically on the receiving end, but instead I'm getting the string representation. This does not seem to be intended behavior.

Possibly related: https://github.com/tauri-apps/tauri/issues/2929

### Reproduction

In the main window:
```ts
type Message = { message: string };

const secondWindow = new WebviewWindow("secondWindow", { /* ... */ });

secondWindow.listen<Message>("message-sent", (e) => console.log(e.payload.message)); // ERROR: `e.payload` is a string
```

In the secondary window:
```ts
const mainWindow = WebviewWindow.getByLabel("main");

mainWindow?.emit("message-sent", { message: "Hello from other window!" });
```

### Expected behavior

`e.payload` should be an object instead of a string.

### Platform and versions

```
Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 106.0.1370.52
  › MSVC: 
      - Visual Studio Build Tools 2022
  › Node.js: 16.17.1
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:5173/
  › framework: Svelte

App directory structure
  ├─ .git
  ├─ .svelte-kit
  ├─ build
  ├─ node_modules
  ├─ src
  ├─ src-tauri
  └─ static
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lucasfernog**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

File: core/tauri/src/endpoints/event.rs [hunk 1]
```diff
@@ -127,10 +128,21 @@ impl Cmd {
...
     event: EventId,
     window_label: Option<WindowLabel>,
-    payload: Option<String>,
+    payload: Option<JsonValue>,
   ) -> super::Result<()> {
     // dispatch the event to Rust listeners
-    context.window.trigger(&event.0, payload.clone());
+    context.window.trigger(
+      &event.0,
+      payload.as_ref().and_then(|p| {
```
Comment (amrbashir) [inline core/tauri/src/endpoints/event.rs:137]: should we maybe add a TODO here to change this to dispatch a `serde_json::Value` in v2?
