### PR TITLE
fix(core): enable CORS on the `asset` protocol, closes #2965

### LINKED ISSUE #2965: Cannot load asset://
### **Describe the bug**
Trying to read a local file with fetch, but the request fails due to CORS error.

```javascript
import { convertFileSrc } from "@tauri-apps/api/tauri";

...

const conv = convertFileSrc("DICOM_FILES/serie_0/IM0");
console.log(conv);
const test = await fetch(conv);
console.log(test);
```

### **To Reproduce**
1. `yarn create tauri-app`
2. Create folder with static files inside `src-tauri` where the app is running
3. Try to read the file

### **Expected behavior**
Able to fetch to local file

### **Screenshots**
image

### **Platform and Versions (required):**
```bash
yarn tauri info
yarn run v1.22.10
warning package.json: No license field
warning ../package.json: No license field
$ tauri info
 app:spawn Running "/Users/antonio/tauri-app/node_modules/@tauri-apps/cli/bin/tauri-cli tauri info" +0ms


Operating System - Mac OS, version 12.0.1 X64

Node.js environment
  Node.js - 12.20.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.8
  yarn - 1.22.10

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/dist
/node_modules
/src-tauri
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src asset: blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:3000
  framework - React

✨  Done in 5.47s.
```

### PR DESCRIPTION
**Pull request by lucasfernog**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [ ] No

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by lucasfernog** [comment]
Must be merged after #2973.

File: core/tauri/src/manager.rs [hunk 1]
```diff
@@ -303,6 +303,17 @@ impl<R: Runtime> WindowManager<R> {
...
+      let window_origin = format!(
+        "{}://{}{}",
+        window_url.scheme(),
+        window_url.host().unwrap(),
+        if let Some(port) = window_url.port() {
+          format!(":{}", port)
+        } else {
+          "".into()
+        }
+      );
```
Comment (antoniotorres) [inline core/tauri/src/manager.rs:316]: This works as expected running `yarn tauri build`, but doesn't work when running `yarn tauri dev`. Same CORS error is displayed on the screen. Don't know how to fix, but my guess is that it is not registering http://localhost:3000 from the vite dev command. I have changed the allowed origin line in my fork to "*" and it works correctly without CORS error. 

https://github.com/antoniotorres/tauri/blob/fix/asset-protocol-cors/core/tauri/src/manager.rs#L307

Comment (lucasfernog) [reply core/tauri/src/manager.rs:316]: ooops i didn't realize i was reassign the url after defining the window origin
