### PR TITLE
fixes iframes in windows causes window.__TAURI_INVOKE__ is not a function error in console.

### LINKED ISSUE #10935: [bug] Regression: iframes in windows causes `window.__TAURI_INVOKE__ is not a function` error in console
### Describe the bug

If the loaded page has an iframe, then in the js console, an error message will be preinted in the console. 

#### Too many error logs printed to js console.

This may be likeley related to https://github.com/tauri-apps/tauri/pull/10300 ?
and  https://github.com/tauri-apps/tauri/issues/10934

### Reproduction

1. Open the tauri demo app and paste the below code for the main index.html
2. Run the app and see the js console.
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"><title>hello</title>
</head>
<body>
<iframe srcdoc="hello"></iframe>
hello world
</body>
</html>
```

### Expected behavior

No error logs in the console.

### Full `tauri info` output

```text
PS E:\code\tauri-test> npm run tauri info

> tauri-app@0.1.0 tauri
> tauri info


[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 128.0.2739.67
    ✔ MSVC:
        - Visual Studio Build Tools 2019
        - Visual Studio Build Tools 2022
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.9.0
    - npm: 10.2.0

[-] Packages
    - tauri [RUST]: 1.7.2
    - tauri-build [RUST]: 1.5.4
    - wry [RUST]: 0.24.11
    - tao [RUST]: 0.16.10
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.6.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../src
    - devPath: ../src
```

### Stack trace

```text
VM89:632 
 Uncaught TypeError: window.__TAURI_INVOKE__ is not a function
    at <anonymous>:632:10
    at <anonymous>:633:3
(anonymous)	@	VM89:632
(anonymous)	@	VM89:633
```

### Additional context

More details can be found here:
https://discord.com/channels/616186924390023171/1258736272814374964

image

### PR DESCRIPTION
**Pull request by hmic**
closes  #10935.

Check if window has __TAURI_INVOKE__ before using it blindly.

### CODE REVIEW

File: core/tauri/scripts/init.js [hunk 1]
```diff
@@ -22,5 +22,5 @@
 
   __RAW_event_initialization_script__
 
-  window.__TAURI_INVOKE__('__initialized', { url: window.location.href })
+  if(window.__TAURI_INVOKE__ !== undefined) window.__TAURI_INVOKE__('__initialized', { url: window.location.href })
```
Comment (lucasfernog) [inline core/tauri/scripts/init.js]:
```suggestion
  if (window.__TAURI_INVOKE__ !== undefined) window.__TAURI_INVOKE__('__initialized', { url: window.location.href })
```

**Review by lucasfernog — APPROVED** [review]
