### PR TITLE
fix(CTA): #1569, manually set tauri script for compatability with older npm

### LINKED ISSUE #1569: CTA + vite/vue fails on npm 6 due to `set-script`
**Describe the bug**
CTA fails on a vite recipe with npm@6. It appears to fail on `set-script` which is only available in npm@7.

**Platform and Versions (please complete the following information):**

OS: mac
Node: ?
NPM: 6
Yarn: n/a
Rustc: n/a

**Stack Trace**

```shell
? Which vite template would you like to use? vue
npx: installed 5 in 4.183s

Scaffolding project in /Users/chris/tmp/tauri-app...

Done. Now run:

  cd tauri-app
  npm install
  npm run dev

===== installing any additional needed deps =====
Installing @tauri-apps/cli...
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN tauri-app@0.0.0 No description
npm WARN tauri-app@0.0.0 No repository field.
npm WARN tauri-app@0.0.0 No license field.

+ @tauri-apps/cli@1.0.0-beta-rc.2
added 475 packages from 357 contributors and audited 475 packages in 27.496s

44 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

===== running tauri init =====

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin,
    bugs, c, cache, ci, cit,
    clean-install,
    clean-install-test, completion,
    config, create, ddp, dedupe,
    deprecate, dist-tag, docs,
    doctor, edit, explore, fund, get,
    help, help-search, hook, i, init,
    install, install-ci-test,
    install-test, it, link, list, ln,
    login, logout, ls, org, outdated,
    owner, pack, ping, prefix,
    profile, prune, publish, rb,
    rebuild, repo, restart, root,
    run, run-script, s, se, search,
    set, shrinkwrap, star, stars,
    start, stop, t, team, test,
    token, tst, un, uninstall,
    unpublish, unstar, up, update, v,
    version, view, whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /Users/chris/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.14.8 /Users/chris/.nvm/versions/node/v14.13.0/lib/node_modules/npm

Did you mean this?
    run-script
Error with command: npm
Error: Error: Command failed with exit code 1: npm set-script tauri tauri
    at /Users/chris/.npm/_npx/15319/lib/node_modules/create-tauri-app/dist/index.js:59:15
    at Generator.throw (<anonymous>)
    at rejected (/Users/chris/.npm/_npx/15319/lib/node_modules/create-tauri-app/dist/index.js:36:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

tmp took 2m8s
```

### PR DESCRIPTION
**Pull request by amrbashir**
**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [ ] No

**The PR fulfills these requirements:**

- [X] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [X] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
Closes #1569

### CODE REVIEW

File: tooling/create-tauri-app/src/helpers/add-tauri-script.ts [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+export async function addTauriScript(appDirectory: string) {
+  const pkgPath = join(appDirectory, "package.json");
+  const pkgString = readFileSync(pkgPath, "utf8");
+  const pkg = JSON.parse(pkgString) as {
+    scripts: {
+      tauri: string;
+    };
+  };
+
+  pkg.scripts.tauri = "tauri";
```
Comment (lucasfernog) [inline tooling/create-tauri-app/src/helpers/add-tauri-script.ts]: what if scripts is undefined?

Comment (amrbashir) [reply tooling/create-tauri-app/src/helpers/add-tauri-script.ts]: good catch, will fix it now

**Review by lucasfernog — APPROVED** [review]
