### PR TITLE
fix(macos): fix regression in `with_menu_on_left_click`, closes #5220

### LINKED ISSUE #5220: [bug] `menuOnLeftClick` isn't working on v1.1.1
### Describe the bug

After upgrading my project to the latest version, I have noticed that the System Tray icon starts opening the context menu when I click on the tray icon

### Reproduction

https://github.com/seahindeniz/tauri-left-click-menu-issue/tree/v1.1.1

1. `npm i`
2. `npm run tauri dev`
3. Click on the system tray icon

### Expected behavior

It should have the same behavior or similar behavior as in the previous version

### Platform and versions

Environment
  › OS: Mac OS 12.5.1 X64
  › Node.js: 16.15.0
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amrbashir**
The regression was introduced in https://github.com/tauri-apps/tauri/commit/4d063ae9ee9538cd6fa5e01b80070c6edf8eaeb9

### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

File: core/tauri-runtime-wry/src/system_tray.rs [hunk 1]
```diff
@@ -105,7 +105,9 @@ pub fn create_tray<T>(
 
   #[cfg(target_os = "macos")]
   {
-    builder = builder.with_icon_as_template(system_tray.icon_as_template)
+    builder = builder
+      .with_icon_as_template(system_tray.icon_as_template)
+      .with_icon_as_template(system_tray.menu_on_left_click)
```
Comment (FabianLars) [inline core/tauri-runtime-wry/src/system_tray.rs]:
```suggestion
      .with_menu_on_left_click(system_tray.menu_on_left_click)
```

Comment (amrbashir) [reply core/tauri-runtime-wry/src/system_tray.rs]: wow copy/pasting is hard for me now 😂, thanks

**Review by lucasfernog — APPROVED** [review]
