### PR TITLE
fix(cli): prevent .app identifier (fix #12674)

### LINKED ISSUE #12674: [bug] Prevent `.app` in identifier
### Describe the bug

This will cause undesired behavior on macOS cause `.app` is a system thing for apps.

Image

### Reproduction

use any `identifier` that ends in `.app` and you'll see macOS thinking it's an app instead of a directory.

### Expected behavior

The tauri runtime should throw an error and if people still want this behavior have a flag to allow it.

### Full `tauri info` output

```text
N/A
```

### Stack trace

```text

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Sky-walkerX**
closes #12674

### CODE REVIEW

**Review by Hacksore — APPROVED** [review]

File: crates/tauri-cli/src/build.rs [hunk 1]
```diff
@@ -150,6 +150,23 @@ pub fn setup(
...
+    if cfg!(target_os = "macos") {
+      log::error!(
+        "The bundle identifier \"{}\" set in `{} identifier` must not end with `.app` on macOS because it conflicts with the application bundle extension.",
+        config_.identifier,
+        bundle_identifier_source
+      );
+      std::process::exit(1);
+    } else {
+      log::warn!(
+        "The bundle identifier \"{}\" set in `{} identifier` ends with `.app`. This is not recommended as it will cause issues on macOS.",
```
Comment (Legend-Master) [inline crates/tauri-cli/src/build.rs]: Maybe we could explain the reason on other platforms as well? (`because it conflicts with the application bundle extension`)

Comment (Sky-walkerX) [reply crates/tauri-cli/src/build.rs]: Done, please check.

**Review by Legend-Master — APPROVED** [review]
Thanks!

Since I'm not familiar with how this really works on macOS, I'll ask @FabianLars to review as well

**Review by FabianLars — APPROVED** [review]

**Comment by Legend-Master** [comment]
I wonder if we should also update the default app id in `create-tauri-app` as it defaults to `com.tauri-app.app` which could cause problems if the user just wants to experiment with things without changing that first

**Comment by Sky-walkerX** [comment]
> I wonder if we should also update the default app id in `create-tauri-app` as it defaults to `com.tauri-app.app` which could cause problems if the user just wants to experiment with things without changing that first

Maybe we could prompt the user to set a custom appId, or just generate one from the project name

**Comment by Legend-Master** [comment]
Technically, we are doing that, just thinking we might want to get rid of the `.app` part by default

image

**Comment by lucasfernog** [comment]
this is actually a breaking change, there's a bunch of apps ending with `.app` that do not really care about the config paths (i'm actually working on one of those :D )

File: crates/tauri-cli/src/build.rs [hunk 2]
```diff
@@ -150,6 +150,23 @@ pub fn setup(
...
+  if config_.identifier.ends_with(".app") {
+    if cfg!(target_os = "macos") {
+      log::error!(
+        "The bundle identifier \"{}\" set in `{} identifier` must not end with `.app` on macOS because it conflicts with the application bundle extension.",
+        config_.identifier,
+        bundle_identifier_source
+      );
+      std::process::exit(1);
+    } else {
+      log::warn!(
```
Comment (lucasfernog) [inline crates/tauri-cli/src/build.rs:162]: I would always warn instead of exiting like above

**Comment by Hacksore** [comment]
Yeah I suppose if you are not caring about macOS and you have a `.app` your builds will now fail which is not desired.

An opt-in CLI flag would not make sense to me but has tauri considered something like compatibility dates in configs so we can introduce semi-breaking changes like this?

[How cloudflare does it via Compatibility dates](https://developers.cloudflare.com/workers/configuration/compatibility-dates/).

**Comment by FabianLars** [comment]
What about those that wkwebview creates?

True about the braking change, didn't really think about that but imo we should still really consider making this a hard error in a future major. (With an opt-out for migrators ig)

**Comment by Legend-Master** [comment]
So I guess we just warn about it for now? I'm not sure if the directory is not usable or just can't be used in finder, if it's just in finder, I guess just a warning would be a better choice for now

**Comment by Sky-walkerX** [comment]
So should I do log::warn and remove log::error and exit from the code block ?

**Comment by Legend-Master** [comment]
Yeah, let's do that, we can always make it a hard fail in the future

**Comment by Sky-walkerX** [comment]
> Yeah, let's do that, we can always make it a hard fail in the future

PR -> #13627, please check

**Comment by lucasfernog** [comment]
> So I guess we just warn about it for now? I'm not sure if the directory is not usable or just can't be used in finder, if it's just in finder, I guess just a warning would be a better choice for now

it's still usable, but Finder shows it as an app and you'd need to actually rightclick -> show package contents to open it
