### PR TITLE
fix(cli): adb port forward error handling, add logs, closes #9509

### LINKED ISSUE #9509: [bug] `error sending request for url (http://192.168.0.x:1420/)` on iOS
### Describe the bug

Whenever I build an app for iOS and run it on a physical device I cannot get the view to load. Using `dev` works alright but `build` never loads. I always get `error sending request for url (http://192.168.0.x:1420/)`

### Reproduction

I'm just using all the vanilla templates from https://beta.tauri.app/guides/create/#using-create-tauri-app. I've specifically tried bun and pnpm for svelte and basic JS.

### Expected behavior

The built app should load on device.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.77.2 (25ef9e3d8 2024-04-09)
    ✔ cargo: 1.77.2 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.12.2
    - pnpm: 9.0.2
    - yarn: 1.22.22
    - npm: 10.5.0
    - bun: 1.1.2

[-] Packages
    - tauri [RUST]: 2.0.0-beta.15
    - tauri-build [RUST]: 2.0.0-beta.12
    - wry [RUST]: 0.39.1
    - tao [RUST]: 0.27.0
    - tauri-cli [RUST]: 2.0.0-alpha.14
    - @tauri-apps/api [NPM]: 2.0.0-beta.8
    - @tauri-apps/cli [NPM]: 2.0.0-beta.13

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - bundler: Vite

[-] iOS
    - Developer Teams: <REDACTED>
```

### Stack trace

_No response_

### Additional context

There's some Discord conversation about this here:
https://discord.com/channels/616186924390023171/1227758916872441856
And here:
https://discord.com/channels/616186924390023171/1230704798488072282/1230718571080974336

### PR DESCRIPTION
**Pull request by lucasfernog**
a port can only be forward to a single device connected with adb, so we must handle:
- multiple devices connected
- port already forwarded to another device

this change also includes better error handling and logs so it's easier for us to triage issues

### CODE REVIEW

File: tooling/cli/src/mobile/android/android_studio_script.rs [hunk 1]
```diff
@@ -85,12 +85,35 @@ pub fn command(options: Options) -> Result<()> {
...
+      // if there's a known target, we should force use it
+      if let Some(target_device) = &cli_options.target_device {
+        run_adb_reverse(&env, &target_device.id, &forward, &forward).with_context(|| {
+          format!(
+            "failed to forward port with adb, is the {} device connected?",
+            target_device.name,
+          )
+        })?;
+      } else if devices.len() == 1 {
+        let device = devices.first().unwrap();
```
Comment (tillmann-crabnebula) [inline tooling/cli/src/mobile/android/android_studio_script.rs:106]: How about making this selectable via flag/config?
Users who know which device could provide the identifier so we do not need to always pick the first one

**Review by tillmann-crabnebula — APPROVED** [review]

**Review by amrbashir — APPROVED** [review]
