### PR TITLE
fix(api.js): fix `os.platform` return on macos and windows, closes #2698

### LINKED ISSUE #2698: "windows" not "win32" for Windows in os.platform() possible values
It's `windows` not `win32` as in the doc.

https://github.com/tauri-apps/tauri/blob/40d08a60fe44fda034a2d3f014fad7cd7a18df1c/tooling/api/src/os.ts#L38

### PR DESCRIPTION
**Pull request by amrbashir**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

File: core/tauri/src/endpoints/operating_system.rs [hunk 1]
```diff
@@ -21,20 +21,32 @@ impl Cmd {
...
 }
+
+#[cfg(os_all)]
+fn os_type() -> String {
+  #[cfg(target_os = "linux")]
+  return "Linux".into();
+  #[cfg(target_os = "windows")]
+  return "Windows_NT".into();
+  #[cfg(target_os = "macos")]
+  return "Darwing".into();
```
Comment (FabianLars) [inline core/tauri/src/endpoints/operating_system.rs]: Should be `Darwin`, right?

Comment (amrbashir) [reply core/tauri/src/endpoints/operating_system.rs]: you are absolutely right. thanks for catching that

Comment (amrbashir) [reply core/tauri/src/endpoints/operating_system.rs]:
```suggestion
  return "Darwin".into();
```

**Review by lucasfernog — APPROVED** [review]
