### PR TITLE
fix: resource path handles `./` path differently

### LINKED ISSUE #14659: [bug] resources path mapping issue
### Describe the bug

Hi, I really love your works, thanks!
I've found bugs about resources path mapping

if the source path is a relative path(starts with like `./` or `../`), then it is appended to the target path
```jsonc
// tauri.conf.json
{
  "bundle": {
    "resources": {
      // it maps all the contents of `some/folder/path` to the `$RESOURCES/sub/`
      "some/folder/path/": "sub/",
      // it maps all the contents of `some/folder/path` to the `$RESOURCES/sub/some/folder/path/`
      "./some/folder/path/": "sub/",
    },
  }
}
```

and if the mapping path starts with `/` or  `../` (of course we should not),
it just append `_root_`, `_up_` directories before the mapping path respectively
```jsonc
// tauri.conf.json
{
  "bundle": {
    "resources": {
      // it maps all the contents of `some/folder/path` to the `$RESOURCES/sub/`
      "some/folder/path/": "sub/",
      // it maps all the contents of `some/folder/path` to the `$RESOURCES/_root_/sub/`
      "some/folder/path/": "/sub/",
      // it maps all the contents of `some/folder/path` to the `$RESOURCES/_up_/sub/`
      "./some/folder/path/": "../sub/",
    },
  }
}
```

thanks

### Reproduction

_No response_

### Expected behavior

_No response_

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 15.6.1 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ Xcode: 26.2
    ✔ rustc: 1.88.0 (6b00bc388 2025-06-23) (Homebrew)
    ✔ cargo: 1.88.0 (Homebrew)
    ✔ rustup: 1.28.2 (e4f3ad6f8 2025-04-28)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 24.4.1
    - pnpm: 10.13.1
    - yarn: 1.22.22
    - npm: 11.1.0

[-] Packages
    - tauri 🦀: 2.9.4, (outdated, latest: 2.9.5)
    - tauri-build 🦀: 2.5.3
    - wry 🦀: 0.53.5
    - tao 🦀: 0.34.5
    - tauri-cli 🦀: 1.6.1 (outdated, latest: 2.9.6)
    - @tauri-apps/api  ⱼₛ: 2.9.1
    - @tauri-apps/cli  ⱼₛ: 2.9.5 (outdated, latest: 2.9.6)

[-] Plugins
    - tauri-plugin-fs 🦀: 2.4.4
    - @tauri-apps/plugin-fs  ⱼₛ: not installed!
    - tauri-plugin-opener 🦀: 2.5.2
    - @tauri-apps/plugin-opener  ⱼₛ: 2.5.2
    - tauri-plugin-single-instance 🦀: 2.3.6
    - @tauri-apps/plugin-single-instance  ⱼₛ: not installed!
    - tauri-plugin-dialog 🦀: 2.4.2
    - @tauri-apps/plugin-dialog  ⱼₛ: 2.4.2
    - tauri-plugin-log 🦀: 2.7.1
    - @tauri-apps/plugin-log  ⱼₛ: 2.7.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

### Stack trace

```text

```

### Additional context

_No response_

### LINKED ISSUE #14723: [bug] Follow-up: `cargo test` still fails on Windows
### Describe the bug

This is a follow-up to #14719.

Although #14720 has been merged and resolved part of the original problem, tests are still failing locally under the same setup.

I wanted to open a separate issue to track the remaining failure, since the original issue was closed automatically when the PR was merged.

I'm happy to provide more details and logs if needed.

- System Name: Windows
- System Version: Windows 11 Home China
- System kernel Version: 26100
- System Arch: x86_64
- Is Admin: false
- Rust toolchain: rustc 1.91.1 (ed61e7d7e 2025-11-07)
- Repository: fresh clone from GitHub

There are two test failures observed locally:

- `resources::tests::resource_paths_errors` fails intermittently (sometimes passes, sometimes fails) under the same setup.

```text

---- resources::tests::resource_paths_errors stdout ----

thread 'resources::tests::resource_paths_errors' (21232) panicked at crates\tauri-utils\src\resources.rs:587:5:
assertion `left == right` failed
  left: 5
 right: 4
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

<details>
<summary>Backtrace</summary>

```text
---- resources::tests::resource_paths_errors stdout ----

thread 'resources::tests::resource_paths_errors' (24668) panicked at crates\tauri-utils\src\resources.rs:587:5:
assertion `left == right` failed
  left: 5
 right: 4
stack backtrace:
   0: std::panicking::panic_handler
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library\std\src\panicking.rs:698
   1: core::panicking::panic_fmt
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library\core\src\panicking.rs:75
   2: core::panicking::assert_failed_inner
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library\core\src\panicking.rs:434
   3: core::panicking::assert_failed<usize,usize>
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library\core\src\panicking.rs:394
   4: tauri_utils::resources::tests::resource_paths_errors::closure$0
             at D:\Code\tauri\crates\tauri-utils\src\resources.rs:587
   5: core::ops::function::FnOnce::call_once<tauri_utils::resources::tests::resource_paths_errors::closure_env$0,tuple$<> >
             at C:\Users\lenovo\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:250
   6: serial_test::serial_code_lock::local_serial_core
             at C:\Users\lenovo\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\serial_test-3.2.0\src\serial_code_lock.rs:36
   7: tauri_utils::resources::tests::resource_paths_errors
             at D:\Code\tauri\crates\tauri-utils\src\resources.rs:564
   8: tauri_utils::resources::tests::resource_paths_errors::closure$0
             at D:\Code\tauri\crates\tauri-utils\src\resources.rs:565
   9: core::ops::function::FnOnce::call_once<tauri_utils::resources::tests::resource_paths_errors::closure_env$0,tuple$<> >
             at C:\Users\lenovo\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:250
  10: core::ops::function::FnOnce::call_once
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    resources::tests::resource_paths_errors

```

</details>

- `resources::tests::resource_paths_iter_slice_allow_walk` is consistently reproducible.

```text

---- resources::tests::resource_paths_iter_slice_allow_walk stdout ----

thread 'resources::tests::resource_paths_iter_slice_allow_walk' (36380) panicked at crates\tauri-utils\src\resources.rs:424:9:
Resource { path: "..\\src\\textures\\ground\\earth.tex", target: "_up_\\src\\textures\\earth.tex" } was expected but not found in [Resource { path: "..\\src\\script.js", target: "_up_\\src\\script.js" }, Resource { path: "..\\src\\assets\\javascript.svg", target: "_up_\\src\\assets\\javascript.svg" }, Resource { path: "..\\src\\assets\\lang\\ar.json", target: "_up_\\src\\assets\\lang\\ar.json" }, Resource { path: "..\\src\\assets\\lang\\en.json", target: "_up_\\src\\assets\\lang\\en.json" }, Resource { path: "..\\src\\assets\\rust.svg", target: "_up_\\src\\assets\\rust.svg" }, Resource { path: "..\\src\\assets\\tauri.svg", target: "_up_\\src\\assets\\tauri.svg" }, Resource { path: "..\\src\\index.html", target: "_up_\\src\\index.html" }, Resource { path: "..\\src\\sounds\\lang\\es.wav", target: "_up_\\src\\sounds\\lang\\es.wav" }, Resource { path: "..\\src\\sounds\\lang\\fr.wav", target: "_up_\\src\\sounds\\lang\\fr.wav" }, Resource { path: "..\\src\\textures\\fire.tex", target: "_up_\\src\\textures\\fire.tex" }, Resource { path: "..\\src\\textures\\ground\\earth.tex", target: "_up_\\src\\textures\\ground\\earth.tex" }, Resource { path: "..\\src\\textures\\ground\\sand.tex", target: "_up_\\src\\textures\\ground\\sand.tex" }, Resource { path: "..\\src\\textures\\water.tex", target: "_up_\\src\\textures\\water.tex" }, Resource { path: "Cargo.toml", target: "Cargo.toml" }, Resource { path: "Tauri.toml", target: "Tauri.toml" }, Resource { path: "tauri.conf.json", target: "tauri.conf.json" }]

```

<details>
<summary>Backtrace</summary>

```text

stack backtrace:
   0: std::panicking::panic_handler
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library\std\src\panicking.rs:698
   1: core::panicking::panic_fmt
            -at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library\core\src\panicking.rs:75
   2: tauri_utils::resources::tests::resource_paths_iter_slice_allow_walk::closure$0
             at D:\Code\tauri\crates\tauri-utils\src\resources.rs:424
   3: core::ops::function::FnOnce::call_once<tauri_utils::resources::tests::resource_paths_iter_slice_allow_walk::closure_env$0,tuple$<> >
             at C:\Users\lenovo\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:250
  4: serial_test::serial_code_lock::local_serial_core
           at C:\Users\lenovo\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\serial_test-3.2.0\src\serial_code_lock.rs:36
5: tauri_utils::resources::tests::resource_paths_iter_slice_allow_walk
            at D:\Code\tauri\crates\tauri-utils\src\resources.rs:362
   6: tauri_utils::resources::tests::resource_paths_iter_slice_allow_walk::closure$0
             at D:\Code\tauri\crates\tauri-utils\src\resources.rs:363
   7: core::ops::function::FnOnce::call_once<tauri_utils::resources::tests::resource_paths_iter_slice_allow_walk::closure_env$0,tuple$<> >
             at C:\Users\lenovo\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:250
   8: core::ops::function::FnOnce::call_once
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

</details>

### Reproduction

git clone https://github.com/tauri-apps/tauri.git
cargo test

### Expected behavior

_No response_

### Full `tauri info` output

```text
This issue is about running `cargo test` in the repository itself,
not about a Tauri application project.
```

### Stack trace

```text

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Legend-Master**
Fix #14659

Also added CI for `tauri-utils`

### CODE REVIEW

File: crates/tauri-utils/src/resources.rs [hunk 1]
```diff
@@ -132,122 +130,133 @@ pub struct ResourcePathsIter<'a> {
...
+          iter: WalkDir::new(&path).into_iter(),
+          current_pattern: if matches!(self.pattern_iter, PatternIter::Map(_)) {
+            Some(path)
+          } else {
+            None
+          },
+        });
+      } else {
+        return Some(self.resource_from_path(path));
+      }
```
Comment (Legend-Master) [inline crates/tauri-utils/src/resources.rs:262]: This replaced `next_current_path`

File: crates/tauri-utils/src/resources.rs [hunk 2]
```diff
@@ -132,122 +130,133 @@ pub struct ResourcePathsIter<'a> {
...
+        // Skip directories
+        if entry.is_dir() {
+          self.next_current_iter()?
+        } else {
+          self.resource_from_path(normalize(&entry))
+        }
+      }
+      Err(error) => Err(error),
+    })
   }
```
Comment (Legend-Master) [inline crates/tauri-utils/src/resources.rs:186]: Grouped walk iter and glob iter into a enum since they're mutually exclusive

File: crates/tauri-utils/src/resources.rs [hunk 3]
```diff
@@ -403,11 +406,11 @@ mod tests {
       // From `../src/textures/**/*`
       (
         "../src/textures/ground/earth.tex",
-        "_up_/src/textures/earth.tex",
+        "_up_/src/textures/ground/earth.tex",
```
Comment (Legend-Master) [inline crates/tauri-utils/src/resources.rs:415]: We didn't run those tests before and they were failing from the very beginning...

File: crates/tauri-utils/src/resources.rs [hunk 4]
```diff
@@ -132,122 +130,133 @@ pub struct ResourcePathsIter<'a> {
...
+      return Err(crate::Error::ResourcePathNotFound(path));
     }
 
     Ok(Resource {
-      path: path.to_path_buf(),
-      target: if let Some((pattern, dest)) = &self.current_pattern {
-        // if processing a directory, preserve directory structure under current_dest
-        if self.walk_iter.is_some() {
-          dest.join(path.strip_prefix(pattern).unwrap_or(path))
-        } else if dest.components().count() == 0 {
```
Comment (Legend-Master) [inline crates/tauri-utils/src/resources.rs:177]: Is this possible? We have normalized this path and `join` for an empty `PathBuf` (`PathBuf::from("")`) should be the same as what's joined to anyways

File: .github/workflows/test-utils.yml [hunk 5]
```diff
@@ -0,0 +1,94 @@
...
+      - name: test
+        if: ${{ !matrix.platform.cross }}
+        # Using --lib --bins --tests to skip doc tests
+        run: cargo ${{ matrix.platform.command }} --target ${{ matrix.platform.target }} ${{ matrix.features.args }} --lib --bins --tests --manifest-path crates/tauri-utils/Cargo.toml
+
+      - name: test (using cross)
+        if: ${{ matrix.platform.cross }}
+        run: |
+          cargo install cross --git https://github.com/cross-rs/cross --rev 51f46f296253d8122c927c5bb933e3c4f27cc317 --locked
+          cross ${{ matrix.platform.command }} --target ${{ matrix.platform.target }} ${{ matrix.features.args }} --lib --bins --tests --manifest-path crates/tauri-utils/Cargo.toml
```
Comment (FabianLars) [inline .github/workflows/test-utils.yml]: can't we merge this into test-core.yml with a manifest-path option in the matrix?

Comment (Legend-Master) [reply .github/workflows/test-utils.yml]: Hmm yeah, we'll also need to setup a `dorny/paths-filter@v2` thing?

Comment (FabianLars) [reply .github/workflows/test-utils.yml]: ah yeah probably, orrr we will simply always build `tauri-utils` first because building the `tauri` crate should be able to reuse its build outputs and therefore not notably slow down CI?

File: crates/tauri-utils/src/resources.rs [hunk 6]
```diff
@@ -132,122 +130,133 @@ pub struct ResourcePathsIter<'a> {
...
-          PathBuf::from(path.file_name().unwrap())
-        } else if self.glob_iter.is_some() {
-          // if processing a glob and current_dest is not empty
-          // we put all globbed paths under current_dest
-          // preserving the file name as it is
-          dest.join(path.file_name().unwrap())
-        } else {
-          dest.clone()
+      path: path.clone(),
+      target: if let Some(dest) = &self.current_dest {
```
Comment (sftse) [inline crates/tauri-utils/src/resources.rs]: If we switch the order of these fields, think we can get rid of the `path.clone()`

File: .github/workflows/test-utils.yml (hunk 5 above)
Comment (Legend-Master) [reply .github/workflows/test-utils.yml]: Building them in order is a bit tricky 🤔 I simply added it to the matrix for now, since they run in parallel, we only loose CI time here without slow downs I think?

Comment (FabianLars) [reply .github/workflows/test-utils.yml]: > we only loose CI time here without slow downs I think?

depends on how many jobs we're running (eg 2 PRs opened at the same time). eg take the plugins-workspace repo for example, where we have to wait for runners to become available for ages if a single PR touches Cargo.lock

> Building them in order is a bit tricky 🤔

can't we have a new step or two above the 2 you modified that builds tauri-utils?

Comment (Legend-Master) [reply .github/workflows/test-utils.yml]: > can't we have a new step or two above the 2 you modified that builds tauri-utils?

brain didn't work 😂

Comment (FabianLars) [reply .github/workflows/test-utils.yml]: at least you have a brain, sometimes i feel like my hands write on their own somehow

Comment (FabianLars) [reply .github/workflows/test-utils.yml]: CI times look good at first glance https://github.com/tauri-apps/tauri/actions/workflows/test-core.yml

**Review by FabianLars — APPROVED** [review]

**Comment by sftse** [comment]
Is it fine that CI wasn't green? Looks like the tests in `platform.rs` should have been deactivated for android?

**Comment by Legend-Master** [comment]
No, missed it completely since we got too many false alarms on the cache fail 🤦‍♂️
