### PR TITLE
fix(macos): run `app.set_theme` on main thread

### LINKED ISSUE #13439: [bug] My program crashed when I called @tauri-apps/api/app setTheme.
### Describe the bug

My program crashed when I called setTheme.
Macbook M2 Pro, MacOS Sonoma 14.5 (23F79), tauri 2.5.1

``` ts
import { setTheme } from '@tauri-apps/api/app';
function switchTheme() {
    setTheme('dark');
}
```

permission declared in `tauri.conf.json`
``` json
"permissions": {
		"core:app:default",
		"core:app:allow-set-app-theme",
}
```
Image

Image

Image

Image

### Reproduction

_No response_

### Expected behavior

_No response_

### Full `tauri info` output

``` log
2025-05-14 18:16:52.927170+0800 qino-feed-client[53816:11363262] [ProcessSuspension] 0x116024900 - ProcessAssertion::acquireSync Failed to acquire RBS assertion 'XPCConnectionTerminationWatchdog' for process with PID=54376, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
2025-05-14 18:16:52.929994+0800 qino-feed-client[53816:11363262] [assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>
2025-05-14 18:16:52.930023+0800 qino-feed-client[53816:11363262] [ProcessSuspension] 0x116024960 - ProcessAssertion::acquireSync Failed to acquire RBS assertion 'WebProcess NearSuspended Assertion' for process with PID=54376, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
2025-05-14 18:16:59.289129+0800 qino-feed-client[53816:11360392] [miscellany] CLIENT ERROR: TUINSRemoteViewController does not override -viewServiceDidTerminateWithError: and thus cannot react to catastrophic errors beyond logging them
Exception: EXC_BREAKPOINT (code=1, subcode=0x19ae7e4f4)
Exception: EXC_BREAKPOINT (code=1, subcode=0x19ae7e4f4)
Exception: EXC_BREAKPOINT (code=1, subcode=0x19ae7e4f4)
```

### PR DESCRIPTION
**Pull request by Legend-Master**
Fix #13439

### CODE REVIEW

File: crates/tauri-runtime-wry/src/lib.rs [hunk 1]
```diff
@@ -2915,18 +2911,18 @@ impl<T: UserEvent> Runtime<T> for Wry<T> {
   }
 
   fn cursor_position(&self) -> Result<PhysicalPosition<f64>> {
-    event_loop_window_getter!(self, EventLoopWindowTargetMessage::CursorPosition)?
+    self
+      .context
+      .main_thread
+      .window_target
+      .cursor_position()
```
Comment (Legend-Master) [inline crates/tauri-runtime-wry/src/lib.rs:2918]: I think this is not needed as `Wry` is `!Send` and can only be used on main thread so reverted it back

**Review by FabianLars — APPROVED** [review]
