### PR TITLE
fix(windows): bundler should not sign non-binaries

### LINKED ISSUE #13341: [bug] SignTool Error: This file format cannot be signed because it is not recognized
### Describe the bug

When `bundle > resources` contains a map where some of the resources are not binary files, attempting to sign on Windows results in the build failing:

```
SignTool Error: This file format cannot be signed because it is not recognized.
```

I believe this is a regression after I recently migrated to latest.

### Reproduction

`tauri.conf.json` should have `bundle > resources` with something like:
```
    "resources": {
      "packaging/README.md": "README.md"
    },
```

`bundle > windows` should also be configured for proper signing, and for reference, I also am using `msi` as the bundle target.

Then build the project: `npm run tauri build`

### Expected behavior

Previously, I don't think files listed under the `resources` map were signed at build time. I think it makes sense that Tauri now attempts to, but it should skip non-binary files.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.26100 x86_64 (X64)
    ✔ WebView2: 135.0.3179.98
    ✔ MSVC: Visual Studio Professional 2022
    ✔ rustc: 1.85.1 (4eb161250 2025-03-15)
    ✔ cargo: 1.85.1 (d73d2caf9 2024-12-31)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: 1.81.0-x86_64-pc-windows-msvc (overridden by 'C:\j\workspace\desktop-app_dwosk_tauri\rust-toolchain.toml')
    - node: 23.11.0
    - npm: 10.9.2

[-] Packages
    - tauri 🦀: 2.5.1
    - tauri-build 🦀: 2.2.0
    - wry 🦀: 0.51.2
    - tao 🦀: 0.33.0
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli : 2.5.0

[-] Plugins
    - tauri-plugin-updater 🦀: 2.7.1
    - @tauri-apps/plugin-updater : not installed!
    - tauri-plugin-single-instance 🦀: 2.2.3
    - @tauri-apps/plugin-single-instance : not installed!
    - tauri-plugin-dialog 🦀: 2.2.1
    - @tauri-apps/plugin-dialog : not installed!
    - tauri-plugin-notification 🦀: 2.2.2
    - @tauri-apps/plugin-notification : not installed!
    - tauri-plugin-process 🦀: 2.2.1
    - @tauri-apps/plugin-process : not installed!
    - tauri-plugin-deep-link 🦀: 2.2.1
    - @tauri-apps/plugin-deep-link : not installed!
    - tauri-plugin-os 🦀: 2.2.1
    - @tauri-apps/plugin-os : not installed!
    - tauri-plugin-fs 🦀: 2.2.1
    - @tauri-apps/plugin-fs : not installed!

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../../frontend/build
    - devUrl: http://localhost:3000/
```

### Stack trace

```text

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Legend-Master**
The bundler will no longer try to sign non-binary and already signed binary files on Windows

Fix #13341

Note: didn't test yet

### CODE REVIEW

File: crates/tauri-bundler/src/bundle/windows/sign.rs [hunk 1]
```diff
@@ -257,3 +257,26 @@ pub fn try_sign<P: AsRef<Path>>(file_path: P, settings: &Settings) -> crate::Res
   }
   Ok(())
 }
+
+/// If the file is signable (is a binary file) and not signed already
+/// (will skip the verification if not on Windows since we can't verify it)
```
Comment (lucasfernog) [inline crates/tauri-bundler/src/bundle/windows/sign.rs:262]: well on macOS we could use `codesign --verify`

Comment (FabianLars) [reply crates/tauri-bundler/src/bundle/windows/sign.rs:262]: on macos we need to sign all files and iirc the signature has to be the same for all files, not sure rn

Comment (Legend-Master) [reply crates/tauri-bundler/src/bundle/windows/sign.rs:262]: > well on macOS we could use `codesign --verify`

Does it verify Windows binaries?

> on macos we need to sign all files and iirc the signature has to be the same for all files, not sure rn

Hmm, does that apply to Windows installers? Or do you mean `codesign --verify` checks a directory instead of a file?

I'm not familiar about how signing works on macOS, how do they store the signing info? ([docs](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html#:~:text=These%20signatures%20are%20stored%20in%20a%20file%20called%20_CodeSignature/CodeResources%20within%20the%20bundle.) says it's stored in `_CodeSignature/CodeResources` which seems to be an xml file)

**Review by FabianLars — APPROVED** [review]
