### PR TITLE
fix(core/path): remove suffix in `basename` only once

### LINKED ISSUE #9064: wired result of `basename(file, extname(file))`
> This issue has been upstreamed from https://github.com/tauri-apps/tauri-docs/issues/1905 

use ext from call `extname` for `basename` return wired result:

``` javascript
const ext = await extname('some-json-file.json'); // 'json'
const nameNoExt = await basename('some-json-file.json', ext); // 'some--file.'
```

Maybe the correct usage is as below?:
```js
const ext = await extname('some-json-file.json'); // 'json'
const nameNoExt = await basename('some-json-file.json', '.' + ext); // some-json-file
```

### PR DESCRIPTION
**Pull request by amrbashir**
closes #9064

### CODE REVIEW

File: tooling/api/src/path.ts [hunk 1]
```diff
@@ -640,12 +639,10 @@ async function extname(path: string): Promise<string> {
  * Returns the last portion of a `path`. Trailing directory separators are ignored.
  * @example
  * ```typescript
- * import { basename, resolveResource } from '@tauri-apps/api/path';
- * const resourcePath = await resolveResource('app.conf');
- * const base = await basename(resourcePath);
+ * import { basename } from '@tauri-apps/api/path';
+ * const base = await basename('path/to/app.conf');
```
Comment (lucasfernog) [inline tooling/api/src/path.ts:643]:
```suggestion
 * const base = await basename('path/to/app.conf');
 * assert(base === 'app.conf');
```

Comment (amrbashir) [reply tooling/api/src/path.ts:643]: this actually added another assert statement, will revert

**Review by lucasfernog — APPROVED** [review]
