### PR TITLE
fix(android): improve error handling for external storage file access

### LINKED ISSUE #14432: [bug] 500 Error when trying to access local video on android
### Describe the bug

ERR_ABORTED 500 (Internal Server Error) when trying to access local video on android, the video file is in the app's external files dir `/storage/emulated/0/Android/data/(myapp)/`

Image

Image
csp:
Image

### Reproduction

`const documentDirectory = await documentDir()
videoUrl.value = convertFileSrc(`${documentDirectory}/demo1.mp4`)`

`<video controls class="video-element" v-if="videoUrl">
                <source :src="videoUrl" type="video/mp4" />
</video>`

### Expected behavior

load video normally 

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.26220 x86_64 (X64)
    ✔ WebView2: 142.0.3595.53
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.88.0 (6b00bc388 2025-06-23)
    ✔ cargo: 1.88.0 (873a06493 2025-05-10)
    ✔ rustup: 1.28.2 (e4f3ad6f8 2025-04-28)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.11.0
    - pnpm: 10.13.1
    - yarn: 4.5.2
    - npm: 10.9.0

[-] Packages
    - tauri 🦀: 2.8.5, (outdated, latest: 2.9.2)
    - tauri-build 🦀: 2.4.1, (outdated, latest: 2.5.1)
    - wry 🦀: 0.53.4, (outdated, latest: 0.53.5)
    - tao 🦀: 0.34.3, (outdated, latest: 0.34.5)
    - @tauri-apps/api : 2.8.0 (outdated, latest: 2.9.0)
    - @tauri-apps/cli : 2.8.4 (outdated, latest: 2.9.3)

[-] Plugins
    - tauri-plugin-dialog 🦀: 2.4.0, (outdated, latest: 2.4.2)
    - @tauri-apps/plugin-dialog : 2.4.2
    - tauri-plugin-opener 🦀: 2.5.0, (outdated, latest: 2.5.2)
    - @tauri-apps/plugin-opener : 2.5.0 (outdated, latest: 2.5.2)
    - tauri-plugin-fs 🦀: 2.4.2, (outdated, latest: 2.4.4)
    - @tauri-apps/plugin-fs : 2.4.4

[-] App
    - build-type: bundle
    - CSP: default-src * 'unsafe-inline' 'unsafe-eval' data: blob:; img-src * data: blob:; media-src * blob:; style-src * 'unsafe-inline'; font-src * data:;
    - frontendDist: ../dist
    - devUrl: http://localhost:5175/
    - framework: Vue.js
    - bundler: Vite
```

### Stack trace

```text

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ish1416**
Fixes 500 error when accessing local video files in Android external storage directory via `convertFileSrc`. Added better error handling and logging for Android external storage access to help diagnose permission and accessibility issues.

Closes #14432

- Enhanced Android-specific error handling in asset protocol handler
- Added file existence checks before attempting to open files  
- Added detailed logging for debugging Android external storage access
- Improved error messages with specific guidance for storage permissions
- Added changelog entry in `.changes` directory

### CODE REVIEW

**Comment by ish1416** [comment]
@FabianLars Can you review this PR?

File: crates/tauri/src/protocol/asset.rs [hunk 1]
```diff
@@ -48,8 +48,45 @@ fn get_response(
...
+  #[cfg(target_os = "android")]
+  {
+    if path.starts_with("/storage/emulated/0/Android/data/") {
+      log::debug!("Attempting to access Android external storage path: {}", path);
+      
+      // Check if the file exists before trying to open it
+      if !std::path::Path::new(&path).exists() {
+        log::error!("File does not exist at path: {}", path);
+        return resp.status(404).body(Vec::new().into()).map_err(Into::into);
+      }
```
Comment (FabianLars) [inline crates/tauri/src/protocol/asset.rs]: this doesn't have to be android-only. it should be valuable information on other platforms as well.

File: crates/tauri/src/protocol/asset.rs [hunk 2]
```diff
@@ -48,8 +48,45 @@ fn get_response(
     return resp.status(403).body(Vec::new().into()).map_err(Into::into);
   }
 
+  // On Android, log additional information for debugging external storage access
+  #[cfg(target_os = "android")]
+  {
+    if path.starts_with("/storage/emulated/0/Android/data/") {
+      log::debug!("Attempting to access Android external storage path: {}", path);
```
Comment (FabianLars) [inline crates/tauri/src/protocol/asset.rs]: i don't think this adds much value

File: crates/tauri/src/protocol/asset.rs [hunk 3]
```diff
@@ -48,8 +48,45 @@ fn get_response(
...
+      // Check if we have read permissions
+      match std::fs::metadata(&path) {
+        Ok(metadata) => {
+          log::debug!("File metadata for {}: size={}, readonly={}", path, metadata.len(), metadata.permissions().readonly());
+        }
+        Err(e) => {
+          log::error!("Failed to get metadata for {}: {}", path, e);
+          return resp.status(500).body(format!("Failed to access file metadata: {}", e).into_bytes().into()).map_err(Into::into);
+        }
+      }
```
Comment (FabianLars) [inline crates/tauri/src/protocol/asset.rs]: this also doesn't have to be android-only.

File: crates/tauri/src/protocol/asset.rs [hunk 4]
```diff
@@ -48,8 +48,45 @@ fn get_response(
...
+      // Check if the file exists before trying to open it
+      if !std::path::Path::new(&path).exists() {
+        log::error!("File does not exist at path: {}", path);
+        return resp.status(404).body(Vec::new().into()).map_err(Into::into);
+      }
+      
+      // Check if we have read permissions
+      match std::fs::metadata(&path) {
+        Ok(metadata) => {
+          log::debug!("File metadata for {}: size={}, readonly={}", path, metadata.len(), metadata.permissions().readonly());
```
Comment (FabianLars) [inline crates/tauri/src/protocol/asset.rs]: This log looks more like the verbosity that's hidden behind the `tracing` feature flag but we're _very_ inconsistent about this :/

File: crates/tauri/src/protocol/asset.rs [hunk 5]
```diff
@@ -48,8 +48,45 @@ fn get_response(
...
   let (mut file, len, mime_type, read_bytes) = crate::async_runtime::safe_block_on(async move {
-    let mut file = File::open(&path).await?;
+    let mut file = match File::open(&path).await {
+      Ok(file) => file,
+      Err(e) => {
+        #[cfg(target_os = "android")]
+        {
+          if path.starts_with("/storage/emulated/0/Android/data/") {
+            log::error!("Failed to open Android external storage file '{}': {}. This may be due to missing storage permissions or the file being inaccessible from the webview context.", path, e);
+            log::error!("Ensure your app has the necessary storage permissions and the file is in an accessible location.");
```
Comment (FabianLars) [inline crates/tauri/src/protocol/asset.rs]: This second line can be derived from the first one so let's remove it to not be _that_ spammy.

**Review by FabianLars — COMMENTED** [review]
thanks for the pr :) a few ideas since most of your code should offer value on other platforms as well, not just android.

**Comment by ish1416** [comment]
@FabianLars Thanks for the review . Ill use your suggestions!

**Comment by ish1416** [comment]
@FabianLars Ive changed in the latest commits whats have been asked can you review it now?

File: crates/tauri/src/protocol/asset.rs [hunk 6]
```diff
@@ -48,8 +48,31 @@ fn get_response(
...
+  // Check if the file exists before trying to open it
+  if !std::path::Path::new(&path).exists() {
+    log::error!("File does not exist at path: {}", path);
+    return resp.status(404).body(Vec::new().into()).map_err(Into::into);
+  }
+  
+  // Check if we have read permissions
+  if let Err(e) = std::fs::metadata(&path) {
+    log::error!("Failed to get metadata for {}: {}", path, e);
+    return resp.status(500).body(format!("Failed to access file metadata: {}", e).into_bytes().into()).map_err(Into::into);
```
Comment (FabianLars) [inline crates/tauri/src/protocol/asset.rs]: maybe we shouldn't use `500` here since that's our fallback on any kind of error. Any other ideas? 403 comes to mind but we already use that above 🤔

Comment (ish1416) [reply crates/tauri/src/protocol/asset.rs]: Okay will sure fix this

Comment (ish1416) [reply crates/tauri/src/protocol/asset.rs]: I used 422 instead of 403.... Its better i Guess

**Review by FabianLars — APPROVED** [review]
