### PR TITLE
fix(cli): Fixes errors on command output, closes #8110

### LINKED ISSUE #8110: "--verbose" parameter cause  "cargo tauri build" error
### Describe the bug

When I add "--verbose" parameter， I got:
```
thread '<unnamed>' panicked at /Users/dev/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tauri-bundler-1.4.5/src/bundle/common.rs:191:46:
byte index 18446744073709551615 is out of bounds of ``
stack backtrace:
Creating disk image...
   0:        0x108beecd1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h65343ad3a85b4e34
   1:        0x1086ec4ab - core::fmt::write::h11839d3825cb5605
   2:        0x108bbc1ae - std::io::Write::write_fmt::h3ab12d369399333c
   3:        0x108bf4479 - std::sys_common::backtrace::print::h405f7c76ca12eb27
   4:        0x108bf40a5 - std::panicking::default_hook::{{closure}}::hed87c355606e1822
   5:        0x108bf3d6f - std::panicking::default_hook::hdf696ec8ea0d65aa
   6:        0x108bf4d65 - std::panicking::rust_panic_with_hook::h7c5059af1af54377
   7:        0x108bf4b44 - std::panicking::begin_panic_handler::{{closure}}::hd658b0e1cffe3d4d
   8:        0x108bf4aa9 - std::sys_common::backtrace::__rust_end_short_backtrace::h3d7834d0cea60a50
   9:        0x108bf4a92 - _rust_begin_unwind
  10:        0x109184073 - core::panicking::panic_fmt::ha9964785de0afb40
  11:        0x1086f4de8 - core::str::slice_error_fail_rt::hdab0588c7b50926d
  12:        0x109184609 - core::str::slice_error_fail::h85725224eed85dfc
  13:        0x108c00135 - std::sys_common::backtrace::__rust_begin_short_backtrace::h02c11099bc04e68c
  14:        0x108c3ed61 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h2e29327d71dd9385
  15:        0x108bf8b39 - std::sys::unix::thread::Thread::new::thread_start::h153c4d3159ba46be
  16:     0x7ff818cc54e1 - __pthread_start
thread 'main' panicked at /Users/dev/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tauri-bundler-1.4.5/src/bundle/common.rs:200:56:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
stack backtrace:
   0:        0x108beecd1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h65343ad3a85b4e34
   1:        0x1086ec4ab - core::fmt::write::h11839d3825cb5605
   2:        0x108bbc1ae - std::io::Write::write_fmt::h3ab12d369399333c
   3:        0x108bf4479 - std::sys_common::backtrace::print::h405f7c76ca12eb27
   4:        0x108bf40a5 - std::panicking::default_hook::{{closure}}::hed87c355606e1822
   5:        0x108bf3d6f - std::panicking::default_hook::hdf696ec8ea0d65aa
   6:        0x108bf4d65 - std::panicking::rust_panic_with_hook::h7c5059af1af54377
   7:        0x108bf4b44 - std::panicking::begin_panic_handler::{{closure}}::hd658b0e1cffe3d4d
   8:        0x108bf4aa9 - std::sys_common::backtrace::__rust_end_short_backtrace::h3d7834d0cea60a50
   9:        0x108bf4a92 - _rust_begin_unwind
  10:        0x109184073 - core::panicking::panic_fmt::ha9964785de0afb40
  11:        0x1091844a1 - core::result::unwrap_failed::h789415aec617156b
  12:        0x108c0776d - <std::process::Command as tauri_bundler::bundle::common::CommandExt>::output_ok::h93d92cf848259b92
  13:        0x108c0aeb4 - tauri_bundler::bundle::bundle_project::h66f302d8f0bb289d
  14:        0x108e4dd72 - tauri_cli::build::command::h9e3f86d7df04e8dd
  15:        0x108635717 - tauri_cli::run::h96836811ba49b9ec
  16:        0x10868be97 - cargo_tauri::main::h92882854e2996cf2
  17:        0x10868b076 - std::sys_common::backtrace::__rust_begin_short_backtrace::h98179b40a915f3c7
  18:        0x10868b963 - _main
  ```
  
And everything returns to normal when I remove the --verbose parameter.
I was unable to reproduce the issue using the official demo. The log provides the file and the line number where the error occurred. I am not familiar with Rust, can you provide some help?

### Reproduction

_No response_

### Expected behavior

_No response_

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 12.6.8 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ Cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.16.0
    - pnpm: 8.4.0
    - yarn: 1.22.19
    - npm: 7.6.0

[-] Packages
    - tauri [RUST]: 1.5.2
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.2
    - tauri-cli [RUST]: 1.5.0
    - @tauri-apps/api [NPM]: 1.5.1
    - @tauri-apps/cli [NPM]: 1.5.0 (outdated, latest: 1.5.6)

[-] App
    - build-type: bundle
    - CSP: unset
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by olivierlemasle**
Command output was fixed in #8042; however it also created two issues:

https://github.com/tauri-apps/tauri/blob/ae75004cee126c4bac332643c49869d2cfe38ad1/tooling/bundler/src/bundle/common.rs#L183-L194

- If `read_line` returns `Err` (which happens if the stream contains an invalid UTF-8 character), `line` is empty and `&line[0..line.len() - 1]` fails (`attempt to subtract with overflow`)
  That happens on macos with `bundle_dmg.sh` when the product name contains a Chinese character or an emoji (cf #8110).
- If the stream ends with no linebreak (just EOF), `line` does not end with `\n`. Therefore, the last byte of the stream is removed. If this is e.g. an ASCII character, it's just one character missing in the output. If the last character is multi-bytes, it throws an error (`byte index xxx is not a char boundary; it is inside xxx`)

### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### Other information

Fixes #8110

### CODE REVIEW

File: tooling/bundler/src/bundle/common.rs [hunk 1]
```diff
@@ -169,10 +169,12 @@ impl CommandExt for Command {
       let mut lines = stdout_lines_.lock().unwrap();
       loop {
         line.clear();
-        if let Ok(0) = stdout.read_line(&mut line) {
```
Comment (lucasfernog) [inline tooling/bundler/src/bundle/common.rs:172]: shouldn't we handle an error here and `continue;` instead?

**Review by lucasfernog — CHANGES_REQUESTED** [review]

File: tooling/bundler/src/bundle/common.rs (hunk 1 above)
Comment (olivierlemasle) [reply tooling/bundler/src/bundle/common.rs:172]: By handling the error, do you mean adding an error message?

E.g.

```rust
match stdout.read_line(&mut line) {
  Ok(0) => break,
  Err(err) => {
    debug!(action = "stdout"; "Err: {}", err);
    continue;
  },
  _ => (),
}
```

(which will print: `Err: stream did not contain valid UTF-8`)

Or something else?

Comment (lucasfernog) [reply tooling/bundler/src/bundle/common.rs:172]: maybe we should just ignore the error and continue the loop instead of printing that message.

Comment (lucasfernog) [reply tooling/bundler/src/bundle/common.rs:172]:
```rust
match stdout.read_line(&mut line) {
  Ok(0) => break,
  Ok(_) => {
    debug!(action = "stderr"; "{}", &line[0..line.len() - 1]); 
    lines.extend(line.as_bytes().to_vec()); 
  },
  _ => (),
}
```

Comment (olivierlemasle) [reply tooling/bundler/src/bundle/common.rs:172]: Thanks @lucasfernog, I've updated the PR.
It's actually equivalent to my first version of the patch, but much clearer without the `continue` instruction.

I'm using `line.trim_end()` instead of `&line[0..line.len() - 1]` because `line` does not end with `\n` if the stream ends without line break, as I wrote above.

**Review by lucasfernog — APPROVED** [review]
Amazing! Thank you ❤️
