### PR TITLE
fix(api): fix dpi types serialization

### LINKED ISSUE #9370: [bug] v2 Failed to set position
### Describe the bug

image

https://github.com/Borber/Tran/blob/6d9b7d3c80c35daee32230f036796f8f44e55689/src/App.tsx#L68

There were no problems with the previous version, but after updating the dependencies, an error was reported.

### Reproduction

Just try this interface directly

### Expected behavior

Correct setting location

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19044 X64
    ✔ WebView2: 123.0.2420.65
    ✔ MSVC: Visual Studio 生成工具 2022
    ✔ rustc: 1.79.0-nightly (88c2f4f5f 2024-04-02)
    ✔ cargo: 1.79.0-nightly (a59aba136 2024-03-28)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: nightly-x86_64-pc-windows-msvc (default)
    - node: 20.11.0
    - pnpm: 8.15.2
    - yarn: 1.22.22
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.14
    - tauri-build [RUST]: 2.0.0-beta.11
    - wry [RUST]: 0.39.0
    - tao [RUST]: 0.27.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.6
    - @tauri-apps/cli [NPM]: 2.0.0-beta.11

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:5046/
    - framework: SolidJS
    - bundler: Vite
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amrbashir**
closes #9370

### CODE REVIEW

File: tooling/api/src/window.ts [hunk 1]
```diff
@@ -1227,15 +1227,15 @@ class Window {
       )
     }
 
+    const value = {} as Record<string, unknown>
+    value[`${size.type}`] = {
```
Comment (i-c-b) [inline tooling/api/src/window.ts:1231]: `setMaxSize` and `setMinSize` need this change as well.

Comment (amrbashir) [reply tooling/api/src/window.ts:1231]: nice catch, pushed it

**Review by FabianLars — DISMISSED** [review]

**Review by FabianLars — APPROVED** [review]
