### PR TITLE
fix(core): global events now reaches window listeners, closes #4493

### LINKED ISSUE #4493: [bug] Differences in behavior between appWindow.listen() and listen()
### Describe the bug

`appWindow.listen()` isn't triggered by `window.emit_to` or `window.emit_all` calls, whereas `listen()` is. My conversation on Discord with @FabianLars suggested this wasn't supposed to the case.

### Reproduction

Given some JS code like:

```js
import { listen } from "@tauri-apps/api/event";
import { appWindow } from "@tauri-apps/api/window";

listen("foo", e => console.log("foo", e);
appWindow.listen("bar", e => console.log("bar", e));
```

and Rust like:

```rust
window.emit("foo", "payload"); // works
window.emit_to("main", "foo", "payload") // works
window.emit_all("foo", "payload") // works

window.emit("bar", "payload"); //works
window.emit_to("main", "bar", "payload") // does NOT work
window.emit_all("bar", "payload") // does NOT work
```

### Expected behavior

_No response_

### Platform and versions

```shell
❯ yarn tauri info                                                                                                                                                                
yarn run v1.22.17                                                                                                                                                                
$ /Users/isaac/code/lqbk/blot3/node_modules/.bin/tauri info                                                                                                                      
                                                                                                                                                                                 
Environment                                                                                                                                                                      
  › OS: Mac OS 12.4.0 X64                                                                                                                                                        
  › Node.js: 18.4.0                                                                                                                                                              
  › npm: 8.12.1                                                                                                                                                                  
  › pnpm: Not installed!                                                                                                                                                         
  › yarn: 1.22.17                                                                                                                                                                
  › rustup: 1.24.3                                                                                                                                                               
  › rustc: 1.61.0                                                                                                                                                                
  › cargo: 1.61.0                                                                                                                                                                
  › Rust toolchain: stable-aarch64-apple-darwin                                                                                                                                  
                                                                                                                                                                                 
Packages                                                                                                                                                                         
  › @tauri-apps/cli [NPM]: 1.0.0                                                                                                                                                 
  › @tauri-apps/api [NPM]: 1.0.1                                                                                                                                                 
  › tauri [RUST]: 1.0.0,                                                                                                                                                         
  › tauri-build [RUST]: 1.0.0,                                                                                                                                                   
  › tao [RUST]: 0.11.2,                                                                                                                                                          
  › wry [RUST]: 0.18.3,                                                                                                                                                          
                                                                                                                                                                                 
App                                                                                                                                                                              
  › build-type: bundle                                                                                                                                                           
  › CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: asset: customprotocol: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'                            
  › distDir: ../dist                                                                                                                                                             
  › devPath: http://localhost:3000/                                                                                                                                              
  › framework: React                                                                                                                                                             
                                                                                                                                                                                 
App directory structure                                                                                                                                                          
  ├─ types                                                                                                                                                                       
  ├─ test                                                                                                                                                                        
  ├─ dist                                                                                                                                                                        
  ├─ node_modules                                                                                                                                                                
  ├─ browser                                                                                                                                                                     
  ├─ public                                                                                                                                                                      
  ├─ src-tauri                                                                                                                                                                   
  └─ src                                                                                                                                                                         
✨  Done in 7.08s.  
```
```


### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lucasfernog**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

This was documented behavior in some functions, but unexpected in other cases. This PR clarifies the event system and also adds examples to all APIs.

### CODE REVIEW

File: core/tauri/src/manager.rs [hunk 1]
```diff
@@ -1112,11 +1112,15 @@ impl<R: Runtime> WindowManager<R> {
     F: Fn(&Window<R>) -> bool,
   {
     assert_event_name_is_valid(event);
+    println!("emit {event}");
```
Comment (amrbashir) [inline core/tauri/src/manager.rs]:
```suggestion
```

File: core/tauri/src/manager.rs [hunk 2]
```diff
@@ -1112,11 +1112,15 @@ impl<R: Runtime> WindowManager<R> {
...
     self
       .windows_lock()
       .values()
       .filter(|&w| filter(w))
-      .try_for_each(|window| window.emit_internal(event, source_window_label, payload.clone()))
+      .try_for_each(|window| {
+        println!("trigger!!");
+        window.emit_internal(event, source_window_label, payload.clone())
+      })
```
Comment (amrbashir) [inline core/tauri/src/manager.rs]:
```suggestion
      .try_for_each(|window| window.emit_internal(event, source_window_label, payload.clone()))
```

**Review by amrbashir — CHANGES_REQUESTED** [review]

**Review by amrbashir — APPROVED** [review]
