### PR TITLE
fix(core): account for `data:`  uri when calculating origin, closes #7078

### LINKED ISSUE #7078: [bug] Data URI is not working when the `window-data-url` feature enabled
### Describe the bug

The [document](https://tauri.app/v1/api/js/window/#url) says the data URL (such as `data:text/html,<html>...`) is supported when enabled by the `window-data-url` feature. But the fact is that an error occurred when loading the data URL.

### Reproduction

Create a `WebviewWindow` in JS, and it will throw an error.

```js
const webview = new WebviewWindow('my-label', {
      url: 'data:text/html,<h3>hello, world</h3>'
});
```

### Expected behavior

Can create WebviewWindnow with the data URL successfully.

### Platform and versions

image

### Stack trace

```text
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/<home>/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.3.0/src/manager.rs:485:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:114:5
   3: core::option::Option<T>::unwrap
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/option.rs:942:21
   4: tauri::manager::WindowManager<R>::prepare_pending_window
             at /home/<home>/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.3.0/src/manager.rs:485:11
   5: tauri::manager::WindowManager<R>::prepare_window
             at /home/<home>/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.3.0/src/manager.rs:1189:15
   6: tauri::window::WindowBuilder<R>::build
             at /home/<home>/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.3.0/src/window.rs:320:19
   7: tauri::endpoints::window::Cmd::create_webview::{{closure}}
             at /home/<home>/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.3.0/src/endpoints/window.rs:219:5
   8: tauri::endpoints::window::Cmd::run::{{closure}}
             at /home/<home>/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.3.0/src/endpoints/window.rs:200:23
   9: tauri::endpoints::Module::run::{{closure}}
             at /home/<home>/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.3.0/src/endpoints.rs:151:11
  10: tauri::hooks::InvokeResolver<R>::return_task::{{closure}}
             at /home/<home>/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.3.0/src/hooks.rs:242:22
  11: tauri::hooks::InvokeResolver<R>::respond_async::{{closure}}
             at /home/<home>/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.3.0/src/hooks.rs:185:70
  12: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/future/future.rs:125:9
  13: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/<home>/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:223:17
  14: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/<home>/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/loom/std/unsafe_cell.rs:14:9
  15: tokio::runtime::task::core::Core<T,S>::poll
             at /home/<home>/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:212:13
  16: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/<home>/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:476:19
  17: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panic/unwind_safe.rs:271:9
  18: std::panicking::try::do_call
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amrbashir**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

File: core/tauri-codegen/src/context.rs [hunk 1]
```diff
@@ -179,6 +179,7 @@ pub fn context_codegen(data: ContextData) -> Result<TokenStream, EmbeddedAssetsE
       .clone()
       .or_else(|| config.tauri.security.csp.clone())
   } else {
+    #[allow(clippy::redundant_clone)]
```
Comment (lucasfernog) [inline core/tauri-codegen/src/context.rs]: The clippy errors here are handled in #7111.

File: core/tauri/src/manager.rs [hunk 2]
```diff
@@ -471,21 +471,21 @@ impl<R: Runtime> WindowManager<R> {
...
-          window_url.host().unwrap(),
-          if let Some(port) = window_url.port() {
-            format!(":{port}")
-          } else {
-            "".into()
-          }
-        )
-      };
+    let window_origin = if window_url.scheme() == "data" {
+      "null".into()
```
Comment (lucasfernog) [inline core/tauri/src/manager.rs:475]: I think we should use `http://localhost` instead. At least that's what wry is using on `navigate_to_string` (macOS) and `load_html` (Linux).

**Review by lucasfernog — CHANGES_REQUESTED** [review]

File: core/tauri/src/manager.rs (hunk 2 above)
Comment (lucasfernog) [reply core/tauri/src/manager.rs:475]: Though actually wry needs some changes for this. The `href` should be the actual data URL string in this case, instead of http://localhost (and we indeed use null here as origin).

**Review by lucasfernog — APPROVED** [review]

File: core/tauri/src/manager.rs (hunk 2 above)
Comment (amrbashir) [reply core/tauri/src/manager.rs:475]: I will open a PR at wry for this.

Comment (lucasfernog) [reply core/tauri/src/manager.rs:475]: The boring thing is we would need to backport it too to land on v1.
