### PR TITLE
fix: premultiply alpha before resizing (fix #14351)

### LINKED ISSUE #14351: [bug] [CLI] Halo/gray fringe appears around icons generated by `tauri icon` when using transparent PNG/SVG input
### Describe the bug

When using `tauri icon` with a transparent-background source (PNG or SVG), the output icons show a faint gray/uneven fringe around curved edges (e.g., circles). Edges show semi-transparent or tinted pixels (light grey) around curved shapes and transparency boundaries.

Image

### Reproduction

1. Create a circular logo image with transparency (e.g., white circle on transparent background) in PNG or export as SVG (example attached).

Image

2. Run `tauri icon`.

3. Examine the generated icons, you’ll see a light gray fringe around the outer edge of the shape.

### Expected behavior

Output icons should have clean edges, outer pixels for transparent regions should be fully transparent and have zero RGB bleed

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.26200 x86_64 (X64)
    ✔ WebView2: 141.0.3537.71
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.90.0 (1159e78c4 2025-09-14)
    ✔ cargo: 1.90.0 (840b83a10 2025-07-30)
    ✔ rustup: 1.28.2 (e4f3ad6f8 2025-04-28)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 22.20.0
    - pnpm: 10.17.1
    - npm: 10.9.3

[-] Packages
    - tauri 🦀: 2.8.5
    - tauri-build 🦀: 2.4.1
    - wry 🦀: 0.53.3, (outdated, latest: 0.53.4)
    - tao 🦀: 0.34.3, (outdated, latest: 0.34.4)
    - @tauri-apps/api : 2.8.0
    - @tauri-apps/cli : 2.8.4

[-] Plugins
    - tauri-plugin-global-shortcut 🦀: 2.3.0
    - @tauri-apps/plugin-global-shortcut : 2.3.0
    - tauri-plugin-dialog 🦀: 2.4.0
    - @tauri-apps/plugin-dialog : 2.4.0
    - tauri-plugin-deep-link 🦀: 2.4.3
    - @tauri-apps/plugin-deep-link : 2.4.3
    - tauri-plugin-updater 🦀: 2.9.0
    - @tauri-apps/plugin-updater : 2.9.0
    - tauri-plugin-store 🦀: 2.4.0
    - @tauri-apps/plugin-store : 2.4.0
    - tauri-plugin-process 🦀: 2.3.0
    - @tauri-apps/plugin-process : 2.3.0
    - tauri-plugin-opener 🦀: 2.5.0
    - @tauri-apps/plugin-opener : 2.5.0
    - tauri-plugin-single-instance 🦀: 2.3.4
    - @tauri-apps/plugin-single-instance : not installed!
    - tauri-plugin-positioner 🦀: 2.3.0
    - @tauri-apps/plugin-positioner : 2.3.0
    - tauri-plugin-fs 🦀: 2.4.2
    - @tauri-apps/plugin-fs : not installed!

[-] App
    - build-type: bundle
    - CSP: ...
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

```text

```

### Additional context

It appears the icon generator’s resizing pipeline (using `image::imageops::resize_exact(...)` with `FilterType::Lanczos3`) operates on non-premultiplied RGBA data, causing RGB “leak” from semi-transparent edge pixels during downscaling. A fix could be to premultiply alpha before resizing, then unpremultiply afterward, and optionally set fully transparent pixels’ RGB to 0 to prevent color bleed while keeping smooth antialiased transparency.

### PR DESCRIPTION
**Pull request by ChaseKnowlden**
Square310x310Logo

Fix #14351

### CODE REVIEW

File: crates/tauri-cli/src/icon.rs [hunk 1]
```diff
@@ -136,7 +136,35 @@ impl Source {
...
+            pixel[1] = 0;
+            pixel[2] = 0;
+          } else {
+            pixel[0] = ((pixel[0] as u32 * 255 + a / 2) / a).min(255) as u8;
+            pixel[1] = ((pixel[1] as u32 * 255 + a / 2) / a).min(255) as u8;
+            pixel[2] = ((pixel[2] as u32 * 255 + a / 2) / a).min(255) as u8;
+          }
+        }
+        Ok(DynamicImage::ImageRgba8(resized))
+      }
```
Comment (Legend-Master) [inline crates/tauri-cli/src/icon.rs]:
```suggestion
      Self::DynamicImage(image) => {
        // Premultiply alpha
        let premultiplied_image = DynamicImage::ImageRgba8(ImageBuffer::from_par_fn(
          image.width(),
          image.height(),
          |x, y| {
            let mut pixel = image.get_pixel(x, y);
            let alpha = pixel.0[3] as f32 / u8::MAX as f32
            pixel.apply_without_alpha(|channel_value| (channel_value as f32 * alpha) as u8);
            pixel
          },
        ));

        let mut resized = premultiplied_image.resize_exact(size, size, FilterType::Lanczos3);

        // Unmultiply alpha
        resized
          .as_mut_rgba8()
          .unwrap()
          .par_pixels_mut()
          .for_each(|pixel| {
            let alpha = pixel.0[3] as f32 / u8::MAX as f32
            pixel.apply_without_alpha(|channel_value| (channel_value as f32 / alpha) as u8);
          });

        Ok(resized)
      }
```

We should be able to rayon here to speed up the process

(the code needs adding rayon to `Cargo.toml` and import `use rayon::iter::ParallelIterator;`)

Also, a comment with a link (for example https://github.com/image-rs/image/issues/1655 or the issue #14351) and some reasoning behind this would be nice

File: crates/tests/acl/fixtures/snapshots/macOS/acl_tests__tests__platform-specific-permissions.snap [hunk 2]
```diff
@@ -3,6 +3,7 @@ source: crates/tests/acl/src/lib.rs
 expression: resolved
 ---
 Resolved {
+    has_app_acl: false,
```
Comment (Legend-Master) [inline crates/tests/acl/fixtures/snapshots/macOS/acl_tests__tests__platform-specific-permissions.snap]: Revert this?

**Review by Legend-Master — COMMENTED** [review]
Thanks! Also do you mind adding a change file?

> https://github.com/tauri-apps/tauri/blob/dev/.changes/README.md

**Comment by its-monotype** [comment]
Hey! Just checking in, do you still have time to work on this?
If not, maybe someone else could continue, or I can try to finish it.
Thanks!

**Comment by Legend-Master** [comment]
@ChaseKnowlden Hi, do you mind if I take over this if you don't have enough time to work on this anymore?

File: crates/tauri-cli/src/icon.rs (hunk 1 above)
Comment (FabianLars) [reply crates/tauri-cli/src/icon.rs]: isn't rayon a bit overkill or did we have that in the deps already?

Comment (Legend-Master) [reply crates/tauri-cli/src/icon.rs]: It's pulled in by image crate already, we are just importing rayon here so we can actually use the rayon iter image crate returned us

Comment (FabianLars) [reply crates/tauri-cli/src/icon.rs]: okok

File: crates/tests/acl/fixtures/snapshots/macOS/acl_tests__tests__platform-specific-permissions.snap (hunk 2 above)
Comment (ChaseKnowlden) [reply crates/tests/acl/fixtures/snapshots/macOS/acl_tests__tests__platform-specific-permissions.snap]: Reverted.

**Review by Legend-Master — APPROVED** [review]
Thanks!
