### PR TITLE
fix(tauri.js) `deps` cmd usage when `npm` is not installed, closes #1037

### LINKED ISSUE #1037: yarn tauri init fails on Ubuntu with (node:581958) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
**Describe the bug**
I'm setting up on Ubuntu 20.04 and already had Rust/Cargo/Yarn/nvm installed. 

Following the getting started for Linux at tauri.studio all is well until `yarn tauri init` which gives the following error. I wonder if it is to do with node version as I've seen things fail at this point, but tauri didn't specify which version it uses. So I tried node v10 and v12, both fail with:

```
$ yarn tauri init 
yarn run v1.22.4
$ /home/mrh/src/tauri/tauri-test/node_modules/.bin/tauri init
[tauri]: running init
? What is your app name? Tauri Test
? What should the window title be? Tauri Test
? What is the url of your dev server? http://localhost:4000
? Where are your web assets (HTML/CSS/JS) located, relative to the "<current dir>/src-tauri" folder
 that will be created? ../dist
 dependency:manager Installing missing dependencies... +0ms
 dependency:cargo-commands "tauri-bundler" is already installed +26ms
 app:spawn [sync] Running "cargo generate-lockfile" +3ms

    Updating crates.io index

 dependency:crates "tauri" is already installed +474ms
(node:583252) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at /home/mrh/src/tauri/tauri-test/node_modules/tauri/dist/api/dependency-manager.js:984:57
    at new Promise (<anonymous>)
    at Object.<anonymous> (/home/mrh/src/tauri/tauri-test/node_modules/tauri/dist/api/dependency-manager.js:982:46)
    at step (/home/mrh/src/tauri/tauri-test/node_modules/tauri/dist/api/dependency-manager.js:932:23)
    at Object.next (/home/mrh/src/tauri/tauri-test/node_modules/tauri/dist/api/dependency-manager.js:913:53)
    at /home/mrh/src/tauri/tauri-test/node_modules/tauri/dist/api/dependency-manager.js:907:71
    at new Promise (<anonymous>)
    at ./src/api/dependency-manager/util.ts.__awaiter (/home/mrh/src/tauri/tauri-test/node_modules/tauri/dist/api/dependency-manager.js:903:12)
    at Object.getNpmPackageVersion (/home/mrh/src/tauri/tauri-test/node_modules/tauri/dist/api/dependency-manager.js:979:12)
    at /home/mrh/src/tauri/tauri-test/node_modules/tauri/dist/api/dependency-manager.js:654:49
(node:583252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:583252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 13.98s.
```

**To Reproduce**
```
sudo apt update && sudo apt install libwebkit2gtk-4.0-dev \
    build-essential \
    curl \
    libssl-dev \
    appmenu-gtk3-module \
    libgtk-3-dev
rustup update stable
cargo install tauri-bundler --force
mkdir tauri-test
cd tauri-test
yarn init
yarn add tauri
yarn tauri init
```

**Platform and Versions (please complete the following information):**

OS: Ubunto 20.04
Node: v12.16.3 (same result with v10.19.0)
NPM: n/a
Yarn: 1.22.4
Rustc: 1.46.0

### PR DESCRIPTION
**Pull request by lucasfernog**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

File: cli/tauri.js/src/api/dependency-manager/util.ts [hunk 1]
```diff
@@ -22,45 +32,51 @@ async function getCrateLatestVersion(crateName: string): Promise<string> {
...
-    const output = String(child.output[1])
-    // eslint-disable-next-line security/detect-non-literal-regexp
-    const matches = new RegExp(packageName + '@(\\S+)', 'g').exec(output)
-    if (matches?.[1]) {
-      resolve(matches[1])
-    } else {
-      resolve(null)
-    }
-  })
+  const child = (await useYarn()) ? crossSpawnSync('yarn', ['list', '--patern', packageName, '--depth', '0']) : crossSpawnSync(
```
Comment (nklayman) [inline cli/tauri.js/src/api/dependency-manager/util.ts]: Why does the npm spawn have the `cwd: appDir`, but the yarn spawn doesn't?

File: cli/tauri.js/src/api/dependency-manager/util.ts [hunk 2]
```diff
@@ -5,9 +5,19 @@ import { sync as crossSpawnSync } from 'cross-spawn'
...
+import { lookpath } from 'lookpath'
 
 const BASE_URL = 'https://docs.rs/crate/'
 
+async function useYarn(): Promise<boolean> {
+  const hasYarnLockfile = existsSync(appResolve.app('yarn.lock'))
+  if (hasYarnLockfile) {
+    return true
+  } else {
+    return (await lookpath('npm')) === undefined
```
Comment (nklayman) [inline cli/tauri.js/src/api/dependency-manager/util.ts]: What happens if the user has neither yarn nor npm installed? Shouldn't an error be thrown? It seems like it will just assume yarn if npm is not installed.

File: cli/tauri.js/package.json [hunk 3]
```diff
@@ -67,6 +67,7 @@
     "isbinaryfile": "4.0.6",
     "jsdom": "16.4.0",
     "lodash": "4.17.20",
+    "lookpath": "^1.1.0",
```
Comment (nklayman) [inline cli/tauri.js/package.json]: Not sure if we should add another dep here (and if we do the version should be locked, not `^`). Instead, we could just exec `npm --version` and if that succeeds then we know npm is installed, otherwise assume it isn't. I think it might be better to add this as a util file instead of adding another dependency.

**Review by nklayman — CHANGES_REQUESTED** [review]
I haven't tested this locally, just looked through the code. It looks good overall, just a few comments/suggestions.
