### PR TITLE
fix(cli): check if version is valid VersionReq before logging error

### LINKED ISSUE #935: "Failed to parse version `2` for crate `tauri`" - fresh install compile errors
Fresh install compile errors:

```
PS Z:\code\amdphreak\bookmark-cleaner-ai\tauri-example> pnpm tauri dev

> tauri-example@0.1.0 tauri Z:\code\amdphreak\bookmark-cleaner-ai\tauri-example
> tauri "dev"

     Running BeforeDevCommand (`pnpm dev`)
       Error Failed to parse version `2` for crate `tauri`
       Error Failed to parse version `2` for crate `tauri-plugin-opener`
...
```

### LINKED ISSUE #14466: [bug] Error Failed to parse version `2` for crate `tauri`
### Describe the bug

<pre>pnpm <font color="#2AA1B3">tauri</font> <font color="#2AA1B3">dev</font>

&gt; testapp@0.1.0 tauri /home/tom/Projects/testapp
&gt; tauri dev

<font color="#26A269"><b>     Running</b></font> BeforeDevCommand (`pnpm dev`)
<font color="#C01C28"><b>       Error</b></font> Failed to parse version `2` for crate `tauri`
<font color="#C01C28"><b>       Error</b></font> Failed to parse version `2` for crate `tauri-plugin-opener`

&gt; testapp@0.1.0 dev /home/tom/Projects/testapp
&gt; vite
</pre>

### Reproduction

```bash
sh (curl -sSL https://create.tauri.app/sh | psub)
cd testapp
pnpm install
pnpm tauri dev
```

### Expected behavior

No Error.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Arch Linux Unknown x86_64 (X64) (gnome on wayland)
    ✔ webkit2gtk-4.1: 2.50.1
    ✔ rsvg2: 2.61.3
    ✔ rustc: 1.90.0 (1159e78c4 2025-09-14)
    ✔ cargo: 1.90.0 (840b83a10 2025-07-30)
    ✔ rustup: 1.28.2 (2025-07-07)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (overridden by environment variable RUSTUP_TOOLCHAIN)
    - node: 25.2.0
    - pnpm: 10.22.0
    - yarn: 1.22.22
    - npm: 11.6.2
    - deno: deno 2.5.5

[-] Packages
    - tauri 🦀: 2.9.3
    - tauri-build 🦀: 2.5.2
    - wry 🦀: 0.53.5
    - tao 🦀: 0.34.5
    - tauri-cli 🦀: 2.9.4
    - @tauri-apps/api  ⱼₛ: 2.9.0
    - @tauri-apps/cli  ⱼₛ: 2.9.4

[-] Plugins
    - tauri-plugin-opener 🦀: 2.5.2
    - @tauri-apps/plugin-opener  ⱼₛ: 2.5.2

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

### Stack trace

```text

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by FabianLars**
This is a bit incomplete because when i tested it earlier this week the pnpm side failed as well but it didn't log errors so i will open a new pr for that when i'm home again.

closes #14466
closes https://github.com/tauri-apps/create-tauri-app/issues/935

### CODE REVIEW

File: crates/tauri-cli/src/info/plugins.rs [hunk 1]
```diff
@@ -72,7 +72,12 @@ pub fn installed_tauri_packages(
         crate_version(tauri_dir, manifest.as_ref(), lock.as_ref(), crate_name).version?;
       let crate_version = semver::Version::parse(&crate_version)
         .inspect_err(|_| {
-          log::error!("Failed to parse version `{crate_version}` for crate `{crate_name}`");
+          // On first run there's no lockfile yet so we get the version requirement from Cargo.toml
+          // In our templates that's `2` which is not a valid semver version but a version requirement.
+          // We only print a warning if the version requirement is invalid but cargo will complain as well.
+          if semver::VersionReq::parse(&crate_version).is_err() {
+            log::error!("Failed to parse version `{crate_version}` for crate `{crate_name}`");
```
Comment (Legend-Master) [inline crates/tauri-cli/src/info/plugins.rs]: I kinda feel like we might want to lower those warnings to `debug` level

**Review by Legend-Master — DISMISSED** [review]

File: crates/tauri-cli/src/info/plugins.rs (hunk 1 above)
Comment (FabianLars) [reply crates/tauri-cli/src/info/plugins.rs]: at that point we might as well remove cause like i said in the comment if versionreq fails, cargo will fail as well

Comment (Legend-Master) [reply crates/tauri-cli/src/info/plugins.rs]: Actually, should we even use the non-locked version here? Since we need the exact version for the check to work, something like `tauri = "2.0.0"` in the `Cargo.toml` would be a false positive

Comment (FabianLars) [reply crates/tauri-cli/src/info/plugins.rs]: That's what I'm saying. The cargo.toml check is absolutely useless. My changes were just to make sure it's valid syntax, not that the version is correct (we're still in the error branch here)

Even if it were = locked it wouldn't offer much value here for that single run where no lock file is present

Comment (FabianLars) [reply crates/tauri-cli/src/info/plugins.rs]: > I kinda feel like we might want to lower those warnings to debug level

Actually gonna do that as well. Just not sure if i should remove the VersionReq check then for the debug log it may be helpful to always know when we're in that inspect_err handler (for example there is a Cargo.lock but we fail to find it)

**Review by Legend-Master — APPROVED** [review]
