### PR TITLE
fix(cli.rs): terminate the beforeDevCommand, closes #2794

### LINKED ISSUE #2794: `beforeDevCommand` is not killed on app exit
### **Describe the bug**
Closing the `tauri dev` app window doesn't close the dev server started with `beforeDevCommand` (confirmed using the `create-react-app` template for `create-tauri-app`)

### **To Reproduce**
1. Create an app using `create-react-app` template
2. Run `tauri dev`
3. Close the app window using the `x` button or alt + f4
4. Run `tauri dev` again. 

### **Expected behavior**
The dev server should be gracefully shut down when the app is closed.

### PR DESCRIPTION
**Pull request by lucasfernog**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [ ] No

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by amrbashir** [comment]
steps I took to produce the issue or at least one of them: 
1. create a svelte project using `create-tauri-app`
2. run `tauri dev`
3. wait only until the svelte devServer is up and before the tauri window is shown then use `Ctrl+C` to terminate the process. 

results: 
- before this PR, the `tauri dev` process exists but it doesn't terminate the `devServer` of svelte and you can't use this terminal session anymore.
- after this PR, using `Ctrl+C` doesn't terminate the process, it instead hangs, sometimes indefinitely and sometimes until the tauri window appears but when that happens the devServer of svelte is killed.

**Comment by probablykasper** [comment]
@amrbashir Could be this:
- https://github.com/sveltejs/template/issues/243

**Comment by amrbashir** [comment]
yeah I think it is related, I talked about it in [discord](https://discord.com/channels/616186924390023171/731495105034321962/901043111332032512) before.

**Comment by amrbashir** [comment]
This issue is driving me crazy, I managed to reproduce it with `vite` in #2998. Same steps, wait for `vite` devServer to run, press `Ctrl+C`, `tauri dev`process is terminated but not `vite` process and the terminal session is unusable.

**Comment by amrbashir** [comment]
A bit of an update, in svelte official template, I found out that they are using `ignore` instead of `inherit` https://github.com/sveltejs/template/blob/4fd09c2a191b017ca9eb9cb9921fa873e95f44b4/rollup.config.js#L21

Switching it to `inherit` doesn't fix the whole issue but at least `Ctrl+C` terminates it properly.

**Comment by lucasfernog** [comment]
@probablykasper can you still reproduce this issue? I couldn't after a lot of attempts.

**Review by FabianLars — DISMISSED** [review]
Seems to work wonderfully on windows 🥳

**Comment by probablykasper** [comment]
@lucasfernog Yes. Tried running `create-react-app` with the Svelte template, then ran `npm run tauri dev` and closed the window it opened. The `npm run tauri dev` command exits, but the `node` process is left running

**Comment by lucasfernog** [comment]
I tried the same steps but I couldn't reproduce it.

**Comment by probablykasper** [comment]
Unable to reproduce it both with this PR and without?

**Comment by probablykasper** [comment]
Screen recording:
https://user-images.githubusercontent.com/11315492/159995391-4316158f-be50-4f8b-b986-fe4cead80886.mp4

**Comment by lucasfernog** [comment]
Looks like we need a better script to kill child processes on Unix (currently `kill -TERM -P {pid}`).

**Comment by probablykasper** [comment]
I don't think there's a better way to do it than that. As long as `SIGTERM` is actually called on the child process, then it should be a bug in the child process if it's not doing what it's told

Best bet might be to instead use a different Svelte template in `create-tauri-app`

**Comment by lucasfernog** [comment]
Yeah but I think we can fix this on our end, I'm testing atm.

**Comment by lucasfernog** [comment]
@probablykasper try again, it works now!

File: tooling/cli/scripts/kill-children.sh [hunk 1]
```diff
@@ -0,0 +1,10 @@
+function getcpid() {
+    cpids=`pgrep -P $1|xargs`
+    for cpid in $cpids;
+    do
+        echo "$cpid"
+        getcpid $cpid
+    done
+}
+
+kill -9 $(getcpid $1)
```
Comment (probablykasper) [inline tooling/cli/scripts/kill-children.sh]: The change is you're calling 9 (SIGKILL) instead of SIGTERM, right? I'm not sure that's a great idea :/

Comment (lucasfernog) [reply tooling/cli/scripts/kill-children.sh]: Let me try with SIGTERM again

Comment (lucasfernog) [reply tooling/cli/scripts/kill-children.sh]: hmm I think there's no other way, either we leave Svelte users with this super annoying bug or we use SIGKILL

Comment (probablykasper) [reply tooling/cli/scripts/kill-children.sh]: I wouldn't want to risk using SIGKILL, could have some rough consequences since it takes away processes' ability to shut down properly :/

As Amr pointed out, the Svelte template might just be spawning it's child process incorrectly

Comment (lucasfernog) [reply tooling/cli/scripts/kill-children.sh]: i'll just revert it, maybe there's a place for us to document it
