### PR TITLE
fix(windows): hide windows on cleanup

### LINKED ISSUE #9610: [bug] window white flashing on exit on Windows
To reproduce, launch api example from the repo, switch the app to dark mode (system preference doesn't matter here, light and dark mode results the same, at least on Windows 10), quit the app from tray icon menu

https://github.com/tauri-apps/tauri/assets/68118705/bef106c6-24c3-487d-9b09-881af2f77679

image

Version: current head 3f0805488506e013e15cfb3cc1cfc8c2c5f84bd2, api example

### PR DESCRIPTION
**Pull request by Legend-Master**
Fix #9610

I don't know if closing the window here will break anything, so I just used `hide`

### CODE REVIEW

File: core/tauri/src/app.rs [hunk 1]
```diff
@@ -772,12 +772,16 @@ macro_rules! shared_app_impl {
...
+        for (_, window) in self.manager.windows() {
           window.resources_table().clear();
         }
-        for (_, webview) in self.manager.webviews().iter() {
+        for (_, webview) in self.manager.webviews() {
           webview.resources_table().clear();
         }
+        #[cfg(windows)]
+        for (_, window) in self.manager.windows() {
+          let _ = window.hide();
```
Comment (amrbashir) [inline core/tauri/src/app.rs]: how will this effect plugins like `window-state`?

Comment (amrbashir) [inline core/tauri/src/app.rs]: can just be moved to the first loop without needing a new loop

Comment (Legend-Master) [reply core/tauri/src/app.rs]: This should be run after all other exit event handlers so should be fine

> ```rust
> let event = on_event_loop_event(&app_handle, RuntimeRunEvent::Exit, &manager);
> callback(&app_handle, event);
> app_handle.cleanup_before_exit();
> ```

**Review by amrbashir — APPROVED** [review]

**Review by amrbashir — APPROVED** [review]
