### PR TITLE
fix(core/dialog): reconstruct path using appropriate separator, closes #8074

### LINKED ISSUE #8074: [bug] api/dialog/dialogOpen parameter defaultPath does not work on Windows with slash separators
### Describe the bug

When calling dialogOpen, defaultPath parameter is supposed to specify which folder will be opened initially.
On windows it works only if backslash is used as path separator, if a forward slash is used then the parameter is ignored.

I realize this is likely a limitation of winapi but it looks like something that is very easy to fix in rust side of the api. Yes, it can be worked around in javascript side but I think Tauri should take care of it since this is both undocumented and not obvious to rootcause when troubleshooting.

### Reproduction

This works

```
dialogOpen({
  title: "Select directory",
  defaultPath: "D:\tmp",
  directory: true,
}
```

This does not
```
dialogOpen({
  title: "Select directory",
  defaultPath: "D:/tmp",
  directory: true,
}
```
and will open the last used directory or current working directory

### Expected behavior

dialogOpen should work with both "\\" and "/" on windows

### Platform and versions

```text
Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 118.0.2088.46
    ✘ Couldn't detect any Visual Studio or VS Build Tools instance with MSVC and SDK components. Download from https://aka.ms/vs/17/release/vs_BuildTools.exe
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ Cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 16.14.2
    - pnpm: 8.6.2
    - npm: 8.5.0

[-] Packages
    - tauri [RUST]: 1.4.0
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0 (outdated, latest: 1.5.1)
    - @tauri-apps/cli [NPM]: 1.4.0 (outdated, latest: 1.5.5)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:8080/
    - framework: React
    - bundler: Webpack
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amrbashir**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

File: core/tauri/src/endpoints/dialog.rs [hunk 1]
```diff
@@ -301,6 +301,7 @@ fn set_default_path(
   mut dialog_builder: FileDialogBuilder,
   default_path: PathBuf,
 ) -> FileDialogBuilder {
+  let default_path: PathBuf = default_path.components().collect();
```
Comment (lucasfernog) [inline core/tauri/src/endpoints/dialog.rs:305]:
```suggestion
  // we need to adjust the separator on Windows: https://github.com/tauri-apps/tauri/issues/8074
  let default_path: PathBuf = default_path.components().collect();
```

**Review by lucasfernog — APPROVED** [review]
