### PR TITLE
fix(plugin): fix android_package_id to follow cli

### LINKED ISSUE #10762: [bug] Plugin template does not match CLI guide
### Describe the bug

Plugin template(mobile.rb):

```
#[cfg(target_os = "android")]
const PLUGIN_IDENTIFIER: &str = "{{ android_package_id }}";
...
  #[cfg(target_os = "android")]
  let handle = api.register_android_plugin(PLUGIN_IDENTIFIER, "ExamplePlugin")?;
```

CLI guide: 

```
Your plugin's init function under src/lib.rs must initialize the Android plugin:

pub fn init<R: Runtime>() -> TauriPlugin<R> {{
  Builder::new("{name}")
    .setup(|app, api| {{
      #[cfg(target_os = "android")]
      let handle = api.register_android_plugin("{identifier}", "ExamplePlugin")?;
      Ok(())
    }})
    .build()
}}
```

### Reproduction

_No response_

### Expected behavior

This must match one of the two. Since the name ExamplePlugin is subject to change, it would be easier to match it to the CLI.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 22.6.0
    - pnpm: 8.9.0
    - yarn: 1.17.3
    - npm: 10.8.2

[-] Packages
    - tauri [RUST]: 2.0.0-rc.6
    - tauri-build [RUST]: 2.0.0-rc.6
    - wry [RUST]: 0.42.0
    - tao [RUST]: 0.29.1
    - tauri-cli [RUST]: 2.0.0-alpha.7
    - @tauri-apps/api [NPM]: 2.0.0-rc.1
    - @tauri-apps/cli [NPM]: 2.0.0-rc.3

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - bundler: Rollup

[-] iOS
    - Developer Teams: ****
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rdlabo**
Match plugin example to CLI.

close https://github.com/tauri-apps/tauri/issues/10762

### CODE REVIEW

File: tooling/cli/templates/plugin/src/mobile.rs [hunk 1]
```diff
@@ -21,7 +18,7 @@ pub fn init<R: Runtime, C: DeserializeOwned>(
   api: PluginApi<R, C>,
 ) -> crate::Result<{{ plugin_name_pascal_case }}<R>> {
   #[cfg(target_os = "android")]
-  let handle = api.register_android_plugin(PLUGIN_IDENTIFIER, "ExamplePlugin")?;
+  let handle = api.register_android_plugin({{ android_package_id }}, "ExamplePlugin")?;
```
Comment (lucasfernog) [inline tooling/cli/templates/plugin/src/mobile.rs]:
```suggestion
  let handle = api.register_android_plugin("{{ android_package_id }}", "ExamplePlugin")?;
```

**Review by lucasfernog — APPROVED** [review]
