### PR TITLE
fix(cli): set current dir to tauri dir before reading config, closes #6771

### LINKED ISSUE #6771: [bug] Relative paths in version field of `tauri.config.json` cannot be processed by `tauri android build`
### Describe the bug

Running `yarn tauri android build` under the project fails with `Error package > version must be a semver string`.

### Reproduction

1. Run
 ```bash
yarn create tauri-app --alpha
cd my-app
yarn
yarn tauri android init
```
2. Goto `src-tauri/tauri.conf.json` and set `package.version` to `../package.json`
3. Run
```bash
yarn tauri android build
```

### Expected behavior

Works fine like `yarn tauri build`.

### Platform and versions

```text
[✔] Environment
    - OS: Ubuntu 22.10 X64
    ✔ webkit2gtk-4.1: 2.38.5
    ✔ rsvg2: 2.54.4
    ✔ rustc: 1.68.2 (9eb3afe9e 2023-03-27)
    ✔ Cargo: 1.68.2 (6feb7c9cf 2023-03-26)
    ✔ rustup: 1.25.2 (17db695f1 2023-02-01)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 18.15.0
    - pnpm: 8.1.1
    - yarn: 3.5.0
    - npm: 9.5.0

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.8
    - tauri-build [RUST]: 2.0.0-alpha.4
    - wry [RUST]: 0.27.3
    - tao [RUST]: 0.18.3
    - @tauri-apps/api [NPM]: 2.0.0-alpha.3
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.8

[-] App
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amrbashir**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

File: tooling/cli/src/dev.rs [hunk 1]
```diff
@@ -148,8 +146,6 @@ pub fn setup(options: &mut Options, mobile: bool) -> Result<AppInterface> {
     None
   };
 
-  set_current_dir(tauri_path).with_context(|| "failed to change current working directory")?;
```
Comment (lucasfernog) [inline tooling/cli/src/dev.rs:151]: The `set_current_dir` call was placed here because we need to parse `options.config` relative to the terminal's CWD instead of the tauri directory. It looks weird to run `tauri build --config ../conf.json` and that path be relative to a different directory.

Comment (amrbashir) [reply tooling/cli/src/dev.rs:151]: Then we need to store the terminal CWD and use where it is needed. I think most of the time, everything should be read relative to tauri.conf.json unless we need it otherwise.

Comment (amrbashir) [reply tooling/cli/src/dev.rs:151]: Should be fine now, although I may spend sometime refactoring the config handling in the CLI and address this todo as well https://github.com/tauri-apps/tauri/blob/8257d7c48148096763e9a2b162832e711f2f8afb/tooling/cli/src/dev.rs#L317-L321 .

File: tooling/cli/src/helpers/config.rs [hunk 2]
```diff
@@ -182,3 +184,26 @@ pub fn get(merge_config: Option<&str>) -> crate::Result<ConfigHandle> {
...
+  use std::env::{current_dir, set_current_dir};
+
+  let old_cwd = current_dir()?;
+  let cwd = CWD.get().unwrap();
+  set_current_dir(cwd)?;
+
+  let ret = match &config {
+    Some(config) if config.starts_with('{') => (Some(config.to_string()), None),
+    Some(config) => (
+      Some(std::fs::read_to_string(config).with_context(|| "failed to read custom configuration")?),
```
Comment (lucasfernog) [inline tooling/cli/src/helpers/config.rs]: instead of the `set_current_dir` thing here we could change `read_to_string(config)` to `read_to_string(cwd.join(config))`. I still feel this solution is kinda weak and could introduce bugs in other places. Maybe we should just duplicate the `set_current_dir` logic to the mobile commands :/

Comment (amrbashir) [reply tooling/cli/src/helpers/config.rs]: sure, reverted the changes and duplicated the logic

**Review by lucasfernog — APPROVED** [review]
