### PR TITLE
fix(core): fix nsis updater unable to launch installers requiring elevation, closes #7184

### LINKED ISSUE #7184: [bug] Updater fails when using an NSIS installer requiring administrator access
### Describe the bug

When I try to have my Tauri application update itself to a new version, it fails when the new version is bundled with an NSIS installer that has installMode `both`. 

What happens is that the update is started, it waits a bit (I'm imagining it's downloading the installer), and eventually quits the old version without launching the new one. No installer for the update shows. When the application is started again, it's still the old version and no update was installed.

When I run the old version of my application with `tauri dev` and I attempt to update from there, I get an error:

```
thread 'tokio-runtime-worker' panicked at 'installer failed to start: Os { code: 740, kind: Uncategorized, message: "The requested operation requires elevation." }', C:\Users\Raph.cargo\git\checkouts\tauri-9dcc2f9152472c1a\076e1a8\core\tauri\src\updater\core.rs:722:10
```

The issue gets resolved when I run my application as administrator, before trying to update.

### Reproduction

1. Set up a Tauri app and update your tauri.conf.json:
  a. Enable the updater functionality
  b. Set the version to 1.0.0
  c. Set the install mode for the NSIS installer to `both` or `perMachine` (Both require elevation)
2. Build a first version 
3. Build a second version with a higher version number (1.1.0)
4. Make the second version available as an update
5. Run the first version and attempt to update to the second version.

Notice how step 5 fails unless you run the first version as administrator.

### Expected behavior

When an outdated version of the application is run without elevation, I would expect the user to be given a UAC prompt when the NSIS installer for the update is run, should it require elevation. 

### Platform and versions

(This is on the latest versions of the `dev` branch)

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 114.0.1823.43
    ✔ MSVC: 
        - Visual Studio Build Tools 2019
        - Visual Studio Build Tools 2022
        - Visual Studio Community 2022
    ✔ rustc: 1.67.0 (fc594f156 2023-01-24)
    ✔ Cargo: 1.67.0 (8ecd4f20a 2023-01-10)
    ✔ rustup: 1.25.1 (bb60b1e89 2022-07-12)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.13.0
    - yarn: 1.22.19
    - npm: 8.19.3

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.1
    - tao [RUST]: git+https://github.com/tauri-apps/tao?branch=v0.16#ed6aab6b1226e56683798732ad01bf3f4658097e (0.16.0)
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist/oyasumivr
    - devPath: http://localhost:4200/
    - framework: Angular
    - bundler: Webpack
```
### Stack trace

```text
thread 'tokio-runtime-worker' panicked at 'installer failed to start: Os { code: 740, kind: Uncategorized, message: "The requested operation requires elevation." }', C:\Users\Raph.cargo\git\checkouts\tauri-9dcc2f9152472c1a\076e1a8\core\tauri\src\updater\core.rs:722:10
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Raphiiko**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

This PR should fix the issue posted in #7184. I am not quite sure if this is the correct solution, but it seems to fix the problem for me. 

Of course this does not solve the problem for existing builds, but I don't see a way for that to be fixed. Users will have to update once by launching the old version as administrator in order to update, or by reinstalling the new version.

### CODE REVIEW

**Comment by Raphiiko** [comment]
~~I am converting this back to draft. It seems to fix the issue in debug mode, but when running in release mode it seems unreliable. I'm not sure why yet.~~

Edit: nvm, I believe this was unrelated.

File: core/tauri/src/updater/core.rs [hunk 1]
```diff
@@ -715,9 +719,11 @@ fn copy_files_and_run<R: Read + Seek>(
     // If it's an `exe` we expect an installer not a runtime.
     if found_path.extension() == Some(OsStr::new("exe")) {
       // Run the EXE
-      Command::new(found_path)
+      Command::new("cmd")
+        .args(&["/C", "start", "", found_path.as_os_str().to_str().unwrap()])
```
Comment (amrbashir) [inline core/tauri/src/updater/core.rs]: could you change this to use `powershell` instead? you will need to determine powershell path using `SYSTEMROOT` env var, move line 794 to line 715 and then do something similar  to line 795

**Review by amrbashir — CHANGES_REQUESTED** [review]
thanks for you contribution

File: core/tauri/src/updater/core.rs [hunk 2]
```diff
@@ -42,9 +42,13 @@ use crate::api::file::Compression;
 #[cfg(target_os = "windows")]
 use std::{
   fs::read_dir,
+  os::windows::process::CommandExt,
   process::{exit, Command},
 };
 
+#[cfg(target_os = "windows")]
+use windows::Win32::System::Threading::DETACHED_PROCESS;
```
Comment (amrbashir) [inline core/tauri/src/updater/core.rs]: from my testings, `DETACHEDPROCESS` was not needed when invoking `cmd` or `powershell` because they bother will call either `start` or `Start-Process` which will launch the installer in a detached process already.

File: core/tauri/src/updater/core.rs (hunk 1 above)
Comment (Raphiiko) [reply core/tauri/src/updater/core.rs]: Woops, my bad, this had fallen off my radar completely. Thanks for updating my pr.

Comment (amrbashir) [reply core/tauri/src/updater/core.rs]: Don't worry about it, thanks for your contribution

**Review by amrbashir — APPROVED** [review]
