### PR TITLE
 fix(event): clear residual js listeners (#8916 )

### LINKED ISSUE #8916: [bug] tauri v2.0.x 'unlisten' work strangely
### Describe the bug

The following js code listens to an event in the useEffect and unlistens the event when the side effect is removed(when refreshing page). 
It works fine in v1, and the haddle time will always be 1.  
But in v2.x, after refreshing the page, the next listen handleTime will still be increased by 1, and all the triggered event have the same eventId. And when the browser console is open, the behavior is even strangler.

```jsx
import { invoke } from "@tauri-apps/api/core";
import { useEffect, useState } from "react";
import { listen } from "@tauri-apps/api/event";

export default function App() {
  const [handleTime, setHandleTime] = useState(0);
  function msgHandler(msg) {
    setHandleTime((prev) => prev + 1);
    console.log(msg);
  }
  useEffect(() => {
    let unlistenPromise = listen("event", msgHandler);

    return async () => {
      const unlisten = await unlistenPromise;
      if (unlisten) {
        unlisten()
          .then((rst) => {
            console.log("call unlisten");
          })
          .catch((e) => {
            alert("call unlisten error: " + e);
          });
      }
    };
  }, []);

  return (
    <>
      {/* This button invoke app.emit("event","msg") */}
      <button
        onClick={() => {
          setHandleTime(0);
          invoke("emit", "msg");
        }}
      >
        emit
      </button>
      <h1>handleTime: {handleTime}</h1>
    </>
  );
}
```

Below are the backend code.
```rust
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use tauri::{generate_handler, Manager, Runtime};

#[tauri::command]
async fn emit<R: Runtime>(
    app: tauri::AppHandle<R>,
    _window: tauri::Window<R>,
) -> Result<(), String> {
    app.emit_all("event", "msg").unwrap();
    Ok(())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
fn main() {
    tauri::Builder::default()
        .invoke_handler(generate_handler![emit])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```
v1 works fine:

https://github.com/tauri-apps/tauri/assets/69547456/3f47015b-d19d-465d-b400-cff2f4214431

v2 :

https://github.com/tauri-apps/tauri/assets/69547456/dbbd2438-9cf7-40c2-a8d7-9426565d6533

https://github.com/tauri-apps/tauri/assets/69547456/f9aa2d20-d298-4b29-a8b6-19acd4d318b4

{2419A211-AF87-48de-BE07-A13563F09179}

### Reproduction

https://github.com/canxin121/test_listen_v1  -> works fine
https://github.com/canxin121/test_listen_v2  -> works strangly

### Expected behavior

The behavior of the v2.x version should be consistent with v1

### Full `tauri info` output

```text
for v1:

[✔] Environment
    - OS: Windows 10.0.19044 X64
    ✔ WebView2: 117.0.2045.43
    ✔ MSVC:
        - Visual Studio Build Tools 2019
        - Visual Studio Community 2022
    ✔ rustc: 1.76.0-nightly (e9013ac0e 2023-12-05)
    ✔ cargo: 1.76.0-nightly (623b78849 2023-12-02)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: nightly-x86_64-pc-windows-msvc (default)
    - node: 21.2.0
    - pnpm: 8.15.2
    - yarn: 1.22.21
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 1.6.0
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.7
    - tauri-cli [RUST]: 2.0.0-beta.1
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.10

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

for v2:
```
[✔] Environment
    - OS: Windows 10.0.19044 X64
    ✔ WebView2: 117.0.2045.43
    ✔ MSVC:
        - Visual Studio Build Tools 2019
        - Visual Studio Community 2022
    ✔ rustc: 1.76.0-nightly (e9013ac0e 2023-12-05)
    ✔ cargo: 1.76.0-nightly (623b78849 2023-12-02)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: nightly-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 21.2.0
    - pnpm: 8.15.2
    - yarn: 1.22.21
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 2.0.0-beta.3      
    - tauri-build [RUST]: 2.0.0-beta.2
    - wry [RUST]: 0.36.0
    - tao [RUST]: 0.25.0
    - tauri-cli [RUST]: 2.0.0-beta.1  
    - @tauri-apps/api [NPM]: 2.0.0-beta.1
    - @tauri-apps/cli [NPM]: 2.0.0-beta.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

In v2.x, with browser console open, got following trace.

```text
chunk-Y2F7D3TJ.js?v=42918a2b:3 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
VM56:1  Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at <anonymous>:87:33
(anonymous) @ VM36:87
Promise.then(异步)
value @ VM36:94
(anonymous) @ VM38:130
action @ VM38:269
(anonymous) @ VM38:278
value @ VM38:252
invoke @ core.js:87
listen @ event.js:70
(anonymous) @ App.jsx:12
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 13 more frames
显示简略信息
VM57:1  Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at <anonymous>:87:33
(anonymous) @ VM36:87
Promise.then(异步)
value @ VM36:94
(anonymous) @ VM38:130
action @ VM38:269
(anonymous) @ VM38:278
value @ VM38:252
invoke @ core.js:87
listen @ event.js:70
(anonymous) @ App.jsx:12
commitHookEffectListMount @ react-dom.development.js:23150
invokePassiveEffectMountInDEV @ react-dom.development.js:25154
invokeEffectsInDev @ react-dom.development.js:27351
commitDoubleInvokeEffectsInDEV @ react-dom.development.js:27330
flushPassiveEffectsImpl @ react-dom.development.js:27056
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 12 more frames
显示简略信息
```

### PR DESCRIPTION
**Pull request by canxin121**
fix clear residual listeners, close #8916 

I noticed that in v1, `js_listeners` were stored on the frontend, so refreshing the page cleans up the original `js_listeners` (note that this doesn't mean that useEffect cleans up the side-effects, as it doesn't have a way to clean up the side-effects before refreshing the page).

However, in v2, `js_listeners` are stored not only in the front end, but also in the back end, and the number of events triggered is determined by the `js_listeners` that stored in the backend, which results in a pileup of `js_listeners` that can't be cleaned up when the page is refreshed.

I added a new js command `unlisten_all` and invoke it at the end of `core.js` to solve this problem. `unlisten_all` only cancels the `js_listeners` at the frontend and backend of the *current window*. 

This fix works fine on my machine, in both single-window and multi-window scenarios.

### CODE REVIEW

**Comment by canxin121** [comment]
[A fixed demo](https://github.com/canxin121/test_listen_v2)

https://github.com/tauri-apps/tauri/assets/69547456/b1a34d18-f9f7-43fe-b918-867ca651a0ae


The origin error demo can be seen at #8916

**Comment by canxin121** [comment]
I just signed the initial commit( dab5723) using `git rebase ---signoff`.

**Comment by lucasfernog** [comment]
I think there's a better way to do this. Handling this via a command called by the frontend might lead to race conditions.
What we could do instead is modify [this closure](https://github.com/tauri-apps/tauri/blob/bc5b5e671a546512f823f1c157421b4c3311dfc0/core/tauri/src/webview/mod.rs#L575) and clear the listeners when the page starts to load.

**Comment by canxin121** [comment]
> I think there's a better way to do this. Handling this via a command called by the frontend might lead to race conditions. What we could do instead is modify [this closure](https://github.com/tauri-apps/tauri/blob/bc5b5e671a546512f823f1c157421b4c3311dfc0/core/tauri/src/webview/mod.rs#L575) and clear the listeners when the page starts to load.

Very good suggestion, I hadn't thought of fixing this bug here before, and now that I've rewritten a new version which doesn't involve any front-end code and no more `unlisten_all_js` for `tauri::command`, it should work as expected.

https://github.com/tauri-apps/tauri/assets/69547456/b003c082-578d-4122-97f9-4ea591140c9d

**Comment by vonPB** [comment]
Been using this for today's development and had no issues at all :)

File: core/tauri/src/event/listener.rs [hunk 1]
```diff
@@ -271,6 +271,18 @@ impl Listeners {
...
+    let inner_listeners = self.inner.as_ref();
+    let mut js_listeners = inner_listeners.js_event_listeners.lock().unwrap();
+    js_listeners
+      .iter_mut()
+      .for_each(|(webview_label, listener)| {
+        if webview_label == source_webview_label {
+          listener.clear()
+        }
+      })
+  }
```
Comment (amrbashir) [inline core/tauri/src/event/listener.rs]: We can just call `.remove(webview_label)`
```suggestion
  pub(crate) fn unlisten_all_js(&self, webview_label: &str) {
    let inner_listeners = self.inner.as_ref();
    let mut js_listeners = inner_listeners.js_event_listeners.lock().unwrap();
    js_listeners.remvoe(webview_label);
  }
```

File: core/tauri/src/event/mod.rs [hunk 2]
```diff
@@ -230,6 +230,24 @@ pub fn unlisten_js_script(
   )
 }
 
+pub fn unlisten_all_js_script(listeners_object_name: &str) -> String {
```
Comment (amrbashir) [inline core/tauri/src/event/mod.rs]: this shouldn't be necessary, since reloads will clear the `window` objects.

File: core/tauri/src/webview/mod.rs [hunk 3]
```diff
@@ -1317,6 +1327,17 @@ fn main() {
     Ok(())
   }
 
+  /// Unregister all JS event listeners.
+  pub(crate) fn unlisten_all_js(&self) -> crate::Result<()> {
+    let listeners: &crate::event::Listeners = self.manager().listeners();
+    listeners.unlisten_all_js(self.label());
+    self.eval(&crate::event::unlisten_all_js_script(
```
Comment (amrbashir) [inline core/tauri/src/webview/mod.rs]: same as above, should not be necessary

File: core/tauri/src/webview/mod.rs [hunk 4]
```diff
@@ -568,17 +568,27 @@ tauri::Builder::default()
...
+        if let Some(w) = manager_.get_webview(&label_) {
+          if let PageLoadEvent::Finished = event {
+            match w.unlisten_all_js() {
+              Ok(_) => {
+                // println!("Clear all residual js listeners when page load.")
+              }
+              Err(e) => {
+                println!("Failed to clear residual js listeners when page load: {e}")
+              }
+            };
```
Comment (amrbashir) [inline core/tauri/src/webview/mod.rs]: Should be okay to ignore the error here.
```suggestion
            let _ = w.unlisten_all_js();
```

**Review by amrbashir — CHANGES_REQUESTED** [review]

**Review by amrbashir — DISMISSED** [review]

**Review by amrbashir — APPROVED** [review]

**Comment by amrbashir** [comment]
Thank you

**Comment by samkearney** [comment]
I'm not sure if this is expected, but this change seems to be causing some kind of race condition on initial load of a React page. I am calling `listen()` from the `componentDidMount()` function of a React component. From my debugging it seems like the following order of events is happening:

1. Page begins to load, `componentDidMount()` is called, my code calls listen() and registers a listener
2. Tauri considers the page to be "loaded". The `on_page_load_handler` is called, and hits a breakpoint inside the function that was added in this PR, `unlisten_all_js()`. This clears the listener my page had registered. (I verified this by inspecting the members in the debugger)
3. Later, my backend code emits some events, but there is nothing to listen to them.

I am new to Tauri, so I may be doing something wrong, but is this expected?

**Comment by FabianLars** [comment]
Hmm, i highly doubt that componentDidMount triggers before DOMContentLoaded. Not 100% sure but still feels wrong to me.

Can you share the code where you listen to and emit the event?

**Comment by samkearney** [comment]
It's closed-source, but let me try to reduce it to something minimal. While I work on that, could you point me to any advice or best practices for places in the lifecycle of a React page where it makes the most sense to set up event listening?

**Comment by FabianLars** [comment]
componentDidMount or useEffect with [] is indeed correct. You just have to unlisten to the event on unmount too. An example for that with useEffect (because i didn't use componentDidMount for years) looks like this
```ts
useEffect(() => {
  const unlisten = listen("someevent", console.log);
  
  return () => {
    unlisten.then( f => f() );
  }
}, []);
```

**Comment by samkearney** [comment]
My minimal reproducer still shows weird behavior, it is not exactly the same as the behavior I described in our larger app code, but it seems like events are arriving out of order and/or there are duplicate copies of some events.

React:
```tsx
import { useEffect, useState } from "react";
import reactLogo from "./assets/react.svg";
import "./App.css";
import { listen } from "@tauri-apps/api/event";

interface EventPayload {
  number: number;
}

function App() {
  const [number, setNumber] = useState(0);

  useEffect(() => {
    const unlisten = listen<EventPayload>("myEvent", (event) => {
      console.log(`Got event: ${event.payload.number}`);
      setNumber(event.payload.number);
    });

    return () => {
      unlisten.then((f) => f());
    };
  }, []);

  return (
    <div className="container">
      <h1>Welcome to Tauri!</h1>

      <div className="row">
        <a href="https://vitejs.dev" target="_blank">
          <img src="/vite.svg" className="logo vite" alt="Vite logo" />
        </a>
        <a href="https://tauri.app" target="_blank">
          <img src="/tauri.svg" className="logo tauri" alt="Tauri logo" />
        </a>
        <a href="https://reactjs.org" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>

      <p>Click on the Tauri, Vite, and React logos to learn more.</p>

      <p>Number: {number}</p>
    </div>
  );
}

export default App;
```

Rust:
```rs
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use std::{thread, time::Duration};

use serde::Serialize;
use tauri::{EventTarget, Manager};

#[derive(Clone, Debug, Serialize)]
struct EventPayload {
    number: i32,
}

fn main() {
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .on_page_load(|page, _| {
            let app_handle = page.app_handle().clone();
            thread::spawn(move || {
                let mut number: i32 = 1;

                loop {
                    app_handle
                        .emit_to(
                            EventTarget::webview_window("main"),
                            "myEvent",
                            EventPayload { number },
                        )
                        .unwrap();
                    number += 1;
                    thread::sleep(Duration::from_millis(50));
                }
            });
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

Results (notice the slight stuttering, this is sometimes better or worse)
stuttering_number

Snippet from console log:

```
App.tsx:15 Got event: 170
App.tsx:15 Got event: 175
App.tsx:15 Got event: 171
App.tsx:15 Got event: 176
App.tsx:15 Got event: 172
App.tsx:15 Got event: 177
App.tsx:15 Got event: 173
App.tsx:15 Got event: 178
App.tsx:15 Got event: 174
App.tsx:15 Got event: 179
App.tsx:15 Got event: 175
App.tsx:15 Got event: 180
App.tsx:15 Got event: 181
App.tsx:15 Got event: 176
App.tsx:15 Got event: 182
App.tsx:15 Got event: 177
App.tsx:15 Got event: 178
App.tsx:15 Got event: 183
App.tsx:15 Got event: 179
App.tsx:15 Got event: 184
App.tsx:15 Got event: 180
App.tsx:15 Got event: 185
App.tsx:15 Got event: 181
App.tsx:15 Got event: 186
App.tsx:15 Got event: 182
App.tsx:15 Got event: 187
App.tsx:15 Got event: 183
App.tsx:15 Got event: 188
App.tsx:15 Got event: 184
App.tsx:15 Got event: 189
App.tsx:15 Got event: 185
App.tsx:15 Got event: 190
App.tsx:15 Got event: 186
App.tsx:15 Got event: 191
App.tsx:15 Got event: 187
App.tsx:15 Got event: 192
App.tsx:15 Got event: 188
App.tsx:15 Got event: 193
App.tsx:15 Got event: 189
App.tsx:15 Got event: 194
App.tsx:15 Got event: 190
App.tsx:15 Got event: 195
App.tsx:15 Got event: 191
App.tsx:15 Got event: 196
App.tsx:15 Got event: 192
App.tsx:15 Got event: 197
App.tsx:15 Got event: 198
App.tsx:15 Got event: 193
```

Almost seems like there are two copies of each event being delivered.

**Comment by samkearney** [comment]
In making my minimal reproducer I realized I had several incorrect assumptions about my code. I think things are working now. Apologies for the spam.

**Comment by gulbanana** [comment]
Here's a repro demonstrating a bug where the listeners are cleaned up too late, destroying new callbacks that were just installed. For me, this works on Windows and on MacOS dev builds, but fails on MacOS production builds.
https://github.com/gulbanana/repro-tauri-macos-events
