### PR TITLE
fix(cli): resolve `bundle > icon` glob when searching for `.ico` for MSI installer

### LINKED ISSUE #11220: [bug] `.ico` generated using tauri icon is incompatible when building on Windows.
### Describe the bug

I generate the icons of my app every time I build it using `tauri icon`, since I don't want to have lots of assets in my repo's commit history and `tauri icon` ensures that they're always strictly appropiate for my app.

Although in the command's output its stated that `.ico` files are generated, building on Windows always fail.

### Reproduction

This reproduction was created using `create-tauri-app`, modifying just the bare minimum to demonstrate the issue (see the commit history for reference:

https://github.com/ferferga/tauri-reproduction-11220

The Windows build log is located in a GitHub Action's run: https://github.com/ferferga/tauri-reproduction-11220/actions/runs/11178007324

### Expected behavior

The icons generated by `tauri icon` work out of the box

### Full `tauri info` output

```text
> tauri-app@0.1.0 tauri
> tauri info


[✔] Environment
    - OS: Debian 12.0.0 x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.44.3
    ✔ rsvg2: 2.54.7
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 20.17.0
    - npm: 10.8.2

[-] Packages
    - tauri 🦀: 2.0.1
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.44.1
    - tao 🦀: 0.30.3
    - @tauri-apps/api : 2.0.1
    - @tauri-apps/cli : 2.0.1

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.1
    - @tauri-apps/plugin-shell : 2.0.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - bundler: Vite
```

### Stack trace

```text
Compiling open v5.3.0
    Finished `release` profile [optimized] target(s) in 10m 06s
    Built application at: D:\a\tauri-issue\tauri-issue\src-tauri\target\release\tauri-app.exe
thread '<unnamed>' panicked at crates\tauri-cli\src\interface\rust.rs:1227:8:
the bundle config must have a `.ico` icon
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Additional context

There are possibly 2 things failing here:

* The icons generated are not suitable
* The [glob pattern](https://github.com/ferferga/tauri-reproduction-11220/blob/master/src-tauri/tauri.conf.json#L30) doesn't work properly in Windows.  However, I also tested `icons/*.ico` without success.

Builds were succeeding in my end before v2 with this setup.

### PR DESCRIPTION
**Pull request by amrbashir**
closes #11220

### CODE REVIEW

File: crates/tauri-bundler/src/bundle/windows/msi/mod.rs [hunk 1]
```diff
@@ -604,7 +604,17 @@ pub fn build_wix_app_installer(
   data.insert("main_binary_path", to_json(main_binary_path));
 
   // copy icon from `settings.windows().icon_path` folder to resource folder near msi
-  let icon_path = copy_icon(settings, "icon.ico", &settings.windows().icon_path)?;
+  #[allow(deprecated)]
+  let icon_path = if settings.windows().icon_path.as_os_str().is_empty() {
```
Comment (lucasfernog) [inline crates/tauri-bundler/src/bundle/windows/msi/mod.rs]:
```suggestion
  let icon_path = if !settings.windows().icon_path.as_os_str().is_empty() {
```

File: crates/tauri-bundler/src/bundle/windows/msi/mod.rs [hunk 2]
```diff
@@ -604,7 +604,17 @@ pub fn build_wix_app_installer(
...
+    settings.windows().icon_path.clone()
+  } else {
+    settings
+      .icon_files()
+      .flatten()
+      .find(|i| i.ends_with(".ico"))
+      .context("Couldn't find a .ico file")?
```
Comment (lucasfernog) [inline crates/tauri-bundler/src/bundle/windows/msi/mod.rs]:
```suggestion
      .context("Couldn't find a .ico icon")?
```

File: crates/tauri-bundler/src/bundle/settings.rs [hunk 3]
```diff
@@ -501,6 +501,7 @@ pub struct WindowsSettings {
   /// Nsis configuration.
   pub nsis: Option<NsisSettings>,
   /// The path to the application icon. Defaults to `./icons/icon.ico`.
+  #[deprecated = "This is used for the MSI installer and will be removed in 3.0.0, use `BundleSettings::icon` field instead."]
```
Comment (lucasfernog) [inline crates/tauri-bundler/src/bundle/settings.rs]:
```suggestion
  #[deprecated = "This is used for the MSI installer and will be removed in 3.0.0, use `BundleSettings::icon` field and make sure a `.ico` icon exists instead."]
```

**Review by lucasfernog — APPROVED** [review]
