### PR TITLE
fix(bundler): sign DLLs

### LINKED ISSUE #11673: [bug] nsis plugins aren't signed
### Describe the bug

Nsis plugins inside nsis installer aren't signed with code signing though I enabled code signing. 
The app was signed, the DLLs and the installer. but the DLLs inside `$PLUGINSDIR` are not signed.
as a result AVs flag them as virus immediately.

### Reproduction

Download sigcheckGUI https://www.majorgeeks.com/mg/getmirror/sigcheckgui,1.html
Download https://github.com/thewh1teagle/vibe/releases/download/v2.6.6/vibe_2.6.6_x64-setup.exe
Extract the app with 7zip and check the signatures of the files 

### Expected behavior

It should be signed by my certificate or by yours (official?)

### Full `tauri info` output

```text
https://github.com/thewh1teagle/vibe
https://github.com/thewh1teagle/vibe/commit/ff020aef26235169541a1ffcea9c0157e8df4311




[✔] Environment
    - node: 20.15.1
    - pnpm: 9.10.0
    - yarn: 1.22.22
    - npm: 10.7.0
    - bun: 1.1.18

[-] Packages
    - tauri 🦀: 2.1.0
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.0
    - tao 🦀: 0.30.6
    - @tauri-apps/api : 2.1.0 (outdated, latest: 2.1.1)
    - @tauri-apps/cli : 2.1.0

[-] Plugins
    - tauri-plugin-updater 🦀: 2.0.2
    - @tauri-apps/plugin-updater : 2.0.0
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : 2.0.1
    - tauri-plugin-store 🦀: 2.1.0
    - @tauri-apps/plugin-store : 2.1.0
    - tauri-plugin-process 🦀: 2.0.1
    - @tauri-apps/plugin-process : 2.0.0
    - tauri-plugin-window-state 🦀: 2.0.2
    - @tauri-apps/plugin-window-state : 2.0.0
    - tauri-plugin-deep-link 🦀: 2.0.1
    - @tauri-apps/plugin-deep-link : 2.0.0
    - tauri-plugin-fs 🦀: 2.0.3
    - @tauri-apps/plugin-fs : 2.0.2
    - tauri-plugin-single-instance 🦀: 2.0.1
    - @tauri-apps/plugin-single-instance : not installed!
    - tauri-plugin-os 🦀: 2.0.1
    - @tauri-apps/plugin-os : 2.0.0
    - tauri-plugin-http 🦀: 2.0.3
    - @tauri-apps/plugin-http : 2.0.0 (outdated, latest: 2.0.1)
    - tauri-plugin-dialog 🦀: 2.0.3
    - @tauri-apps/plugin-dialog : 2.0.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

_No response_

### Additional context

I noticed that virustotal flag the nsis plugins as a virus. 
By the way signing with self signed certificate is better than unsigned! now windows defender didn't blocked it and virus total has less false positives 

https://code.videolan.org/videolan/vlc/-/issues/27469

### PR DESCRIPTION
**Pull request by thewh1teagle**
Fix https://github.com/tauri-apps/tauri/issues/11673

Now it's signed after bundling:

Log:

<details>

```console
..\..\tauri\target\debug\cargo-tauri.exe bundle
    Signing D:\vibe\target\release\vibe.exe
    Signing D:\vibe\target\release\vibe.exe with identity "45DCFF335BB538C58489BD03BF167D29DDA53110"
    Info "Done Adding Additional Store\r\nSuccessfully signed: D:\\vibe\\target\\release\\vibe.exe\r\r\n"
    Warn NSIS directory contains mis-hashed files. Redownloading them.
    Downloading https://github.com/tauri-apps/nsis-tauri-utils/releases/download/nsis_tauri_utils-v0.4.1/nsis_tauri_utils.dll
    Info validating hash
    Info Target: x64
    Info Signing NSIS plugins
    Signing C:\Users\User\AppData\Local\tauri\NSIS\Plugins\x86-ansi\NSISdl.dll
    Signing C:\Users\User\AppData\Local\tauri\NSIS\Plugins\x86-ansi\NSISdl.dll with identity "45DCFF335BB538C58489BD03BF167D29DDA53110"
    Info "Done Adding Additional Store\r\nSuccessfully signed: C:\\Users\\User\\AppData\\Local\\tauri\\NSIS\\Plugins\\x86-ansi\\NSISdl.dll\r\r\n"
    Signing C:\Users\User\AppData\Local\tauri\NSIS\Plugins\x86-ansi\StartMenu.dll
    Signing C:\Users\User\AppData\Local\tauri\NSIS\Plugins\x86-ansi\StartMenu.dll with identity "45DCFF335BB538C58489BD03BF167D29DDA53110"
    Info "Done Adding Additional Store\r\nSuccessfully signed: C:\\Users\\User\\AppData\\Local\\tauri\\NSIS\\Plugins\\x86-ansi\\StartMenu.dll\r\r\n"
    Signing C:\Users\User\AppData\Local\tauri\NSIS\Plugins\x86-ansi\System.dll
    Signing C:\Users\User\AppData\Local\tauri\NSIS\Plugins\x86-ansi\System.dll with identity "45DCFF335BB538C58489BD03BF167D29DDA53110"
    Info "Done Adding Additional Store\r\nSuccessfully signed: C:\\Users\\User\\AppData\\Local\\tauri\\NSIS\\Plugins\\x86-ansi\\System.dll\r\r\n"
    Signing C:\Users\User\AppData\Local\tauri\NSIS\Plugins\x86-ansi\nsDialogs.dll
    Signing C:\Users\User\AppData\Local\tauri\NSIS\Plugins\x86-ansi\nsDialogs.dll with identity "45DCFF335BB538C58489BD03BF167D29DDA53110"
    Info "Done Adding Additional Store\r\nSuccessfully signed: C:\\Users\\User\\AppData\\Local\\tauri\\NSIS\\Plugins\\x86-ansi\\nsDialogs.dll\r\r\n"
    Signing C:\Users\User\AppData\Local\tauri\NSIS\Plugins\x86-unicode\NSISdl.dll
    Signing C:\Users\User\AppData\Local\tauri\NSIS\Plugins\x86-unicode\NSISdl.dll with identity "45DCFF335BB538C58489BD03BF167D29DDA53110"
    Info "Done Adding Additional Store\r\nSuccessfully signed: C:\\Users\\User\\AppData\\Local\\tauri\\NSIS\\Plugins\\x86-unicode\\NSISdl.dll\r\r\n"
    Signing C:\Users\User\AppData\Local\tauri\NSIS\Plugins\x86-unicode\StartMenu.dll
    Signing C:\Users\User\AppData\Local\tauri\NSIS\Plugins\x86-unicode\StartMenu.dll with identity "45DCFF335BB538C58489BD03BF167D29DDA53110"
    Info "Done Adding Additional Store\r\nSuccessfully signed: C:\\Users\\User\\AppData\\Local\\tauri\\NSIS\\Plugins\\x86-unicode\\StartMenu.dll\r\r\n"
    Signing C:\Users\User\AppData\Local\tauri\NSIS\Plugins\x86-unicode\System.dll
    Signing C:\Users\User\AppData\Local\tauri\NSIS\Plugins\x86-unicode\System.dll with identity "45DCFF335BB538C58489BD03BF167D29DDA53110"
    Info "Done Adding Additional Store\r\nSuccessfully signed: C:\\Users\\User\\AppData\\Local\\tauri\\NSIS\\Plugins\\x86-unicode\\System.dll\r\r\n"
    Signing C:\Users\User\AppData\Local\tauri\NSIS\Plugins\x86-unicode\nsDialogs.dll
    Signing C:\Users\User\AppData\Local\tauri\NSIS\Plugins\x86-unicode\nsDialogs.dll with identity "45DCFF335BB538C58489BD03BF167D29DDA53110"
    Info "Done Adding Additional Store\r\nSuccessfully signed: C:\\Users\\User\\AppData\\Local\\tauri\\NSIS\\Plugins\\x86-unicode\\nsDialogs.dll\r\r\n"
    Signing C:\Users\User\AppData\Local\tauri\NSIS\Plugins\x86-unicode\nsis_tauri_utils.dll
    Signing C:\Users\User\AppData\Local\tauri\NSIS\Plugins\x86-unicode\nsis_tauri_utils.dll with identity "45DCFF335BB538C58489BD03BF167D29DDA53110"
    Info "Done Adding Additional Store\r\nSuccessfully signed: C:\\Users\\User\\AppData\\Local\\tauri\\NSIS\\Plugins\\x86-unicode\\nsis_tauri_utils.dll\r\r\n"
    Running makensis.exe to produce D:\vibe\target\release\bundle\nsis\vibe_2.6.6_x64-setup.exe
Done Adding Additional Store
Successfully signed: C:\Users\User\AppData\Local\Temp\nst3640.tmp
    Signing D:\vibe\target\release\bundle\nsis\vibe_2.6.6_x64-setup.exe
    Signing D:\vibe\target\release\bundle\nsis\vibe_2.6.6_x64-setup.exe with identity "45DCFF335BB538C58489BD03BF167D29DDA53110"
    Info "Done Adding Additional Store\r\nSuccessfully signed: D:\\vibe\\target\\release\\bundle/nsis/vibe_2.6.6_x64-setup.exe\r\r\n"
    Finished 1 bundle at:
        D:\vibe\target\release\bundle\nsis\vibe_2.6.6_x64-setup.exe
```
</details>

This can potentially fix some issues with https://github.com/tauri-apps/tauri/issues/2486
Btw I recommend to everyone always sign the exe even with self signed certificate instead of publishing unsigned binaries that usually flagged immediately as a virus by Windows AVs

### CODE REVIEW

File: crates/tauri-bundler/src/bundle/windows/nsis/mod.rs [hunk 1]
```diff
@@ -51,6 +51,14 @@ const NSIS_REQUIRED_FILES: &[&str] = &[
   "Include/nsDialogs.nsh",
   "Include/WinMessages.nsh",
 ];
+#[cfg(target_os = "windows")]
+const NSIS_PLUGIN_DLLS: &[&str] = &[
+  "NSISdl.dll",
+  "StartMenu.dll",
+  "System.dll",
+  "nsDialogs.dll",
```
Comment (amrbashir) [inline crates/tauri-bundler/src/bundle/windows/nsis/mod.rs:62]: all these dlls are provided by NSIS and shouldn't cause a problem

File: crates/tauri-bundler/src/bundle/windows/nsis/mod.rs [hunk 2]
```diff
@@ -51,6 +51,14 @@ const NSIS_REQUIRED_FILES: &[&str] = &[
...
+  "nsis_tauri_utils.dll",
```
Comment (amrbashir) [inline crates/tauri-bundler/src/bundle/windows/nsis/mod.rs]: I suspect this one to be though, maybe we should only sign this

**Review by amrbashir — CHANGES_REQUESTED** [review]

File: crates/tauri-bundler/src/bundle/windows/nsis/mod.rs (hunk 2 above)
Comment (amrbashir) [reply crates/tauri-bundler/src/bundle/windows/nsis/mod.rs]: or maybe we should sign nsis-tauri-utils.dll in https://github.com/tauri-apps/nsis-tauri-utils instead

Comment (thewh1teagle) [reply crates/tauri-bundler/src/bundle/windows/nsis/mod.rs]: I want to sign them all just for any case. Maybe we should add option to enable signNsisPlugins?

Comment (thewh1teagle) [reply crates/tauri-bundler/src/bundle/windows/nsis/mod.rs]: I remember that AVs flagged the plugins DLLs as malware just because they are not signed

Comment (amrbashir) [reply crates/tauri-bundler/src/bundle/windows/nsis/mod.rs]: let's try with signing all then.

File: crates/tauri-bundler/src/bundle/windows/nsis/mod.rs [hunk 3]
```diff
@@ -517,6 +525,29 @@ fn build_nsis_app_installer(
...
+      if NSIS_PLUGIN_DLLS.contains(
+        &path
+          .file_name()
+          .unwrap_or_default()
+          .to_string_lossy()
+          .as_ref(),
+      ) {
+        try_sign(&path, settings)?;
+      }
+    }
```
Comment (amrbashir) [inline crates/tauri-bundler/src/bundle/windows/nsis/mod.rs]: we know the paths of these dlls, no need to glob
```suggestion
    for dll in NSIS_PLUGIN_DLLS {
      let path = _nsis_toolset_path.join("Plugins/x86-unicode").join(dll);
      try_sign(&path, settings)?;
    }
```

File: crates/tauri-bundler/src/bundle/windows/nsis/mod.rs [hunk 4]
```diff
@@ -517,6 +525,29 @@ fn build_nsis_app_installer(
   ));
   fs::create_dir_all(nsis_installer_path.parent().unwrap())?;
 
+  #[cfg(target_os = "windows")]
```
Comment (amrbashir) [inline crates/tauri-bundler/src/bundle/windows/nsis/mod.rs]: NSIS can be built and signed on Unix and macOS, let's remove this cfg

**Review by amrbashir — CHANGES_REQUESTED** [review]
Could you also add a change file in .changes directory?

**Comment by thewh1teagle** [comment]
Updated

File: crates/tauri-bundler/src/bundle/windows/nsis/mod.rs [hunk 5]
```diff
@@ -51,6 +51,16 @@ const NSIS_REQUIRED_FILES: &[&str] = &[
...
+#[cfg(target_os = "windows")]
+const NSIS_PLUGIN_FILES: &[&str] = &[
+  "NSISdl.dll",
+  "StartMenu.dll",
+  "System.dll",
+  "nsDialogs.dll",
+  "nsis_tauri_utils.dll",
+];
+#[cfg(not(target_os = "windows"))]
+const NSIS_PLUGIN_FILES: &[&str] = &[];
```
Comment (amrbashir) [inline crates/tauri-bundler/src/bundle/windows/nsis/mod.rs]: hmmm, this doesn't sound right, this makes it so that signing works on Windows but not on other platforms, we should at least sign `nsis_tauri_utils.dll` on other platforms

**Review by amrbashir — CHANGES_REQUESTED** [review]

File: crates/tauri-bundler/src/bundle/windows/nsis/mod.rs (hunk 5 above)
Comment (thewh1teagle) [reply crates/tauri-bundler/src/bundle/windows/nsis/mod.rs]: But other platforms doesn't have DLLs. I'm not sure what do you suggest we sign on other platform?

Comment (amrbashir) [reply crates/tauri-bundler/src/bundle/windows/nsis/mod.rs]: other platforms can cross-build a windows NSIS installer, and these dlls exist, see https://tauri.app/distribute/windows-installer/#install-nsis

Comment (thewh1teagle) [reply crates/tauri-bundler/src/bundle/windows/nsis/mod.rs]: Fixed

**Comment by thewh1teagle** [comment]
Just a reminder. I still get many false positive detections and I believe that should fix most of them. Hope you can merge it soon.

Update: that's what I do meanwhile:

```console
# Import certificate
[IO.File]::WriteAllBytes('cert.pfx', [Convert]::FromBase64String($env:WINDOWS_CERTIFICATE))
Import-PfxCertificate -Exportable -FilePath "cert.pfx" -CertStoreLocation 'cert:\CurrentUser\My' -Password (ConvertTo-SecureString -String $env:WINDOWS_CERTIFICATE_PASSWORD -Force -AsPlainText)

# Sign resources
$signtoolPath = (Get-ChildItem "C:\Program Files (x86)\Windows Kits\10\bin\" -Filter "signtool.exe" -Recurse | Where-Object FullName -like "*\x64\signtool.exe" | Select-Object -First 1).FullName
&$signtoolPath sign /f cert.pfx /p $env:WINDOWS_CERTIFICATE_PASSWORD /tr http://timestamp.digicert.com /td sha256 /fd sha256 desktop\src-tauri\ffmpeg\bin\x64\*
# Sign nsis plugin DLLs
Get-ChildItem -Path "$env:LOCALAPPDATA\tauri\NSIS\Plugins" -Filter '*.dll' -Recurse | ForEach-Object { 
    &$signtoolPath sign /f cert.pfx /p $env:WINDOWS_CERTIFICATE_PASSWORD /tr http://timestamp.digicert.com /td sha256 /fd sha256 $_.FullName
}
```

**Comment by thewh1teagle** [comment]
I noticed now that caching won't work if we sign the plugin files

https://github.com/tauri-apps/tauri/blob/dev/crates/tauri-bundler/src/bundle/windows/nsis/mod.rs#L88

It will redownlod them each time we bundle.
maybe we should cache them in directory derived from the URL

**Comment by amrbashir** [comment]
@thewh1teagle then we should copy them next to the generated installer.nsi and sign these copies instead.

**Review by lucasfernog — APPROVED** [review]
thank you!

**Comment by linguofeng** [comment]
https://github.com/tauri-apps/tauri/issues/13341

File: crates/tauri-bundler/src/bundle/windows/nsis/mod.rs [hunk 6]
```diff
@@ -650,6 +744,10 @@ fn generate_resource_data(settings: &Settings) -> crate::Result<ResourcesMap> {
     }
     added_resources.push(resource_path.clone());
 
+    if settings.can_sign() {
+      try_sign(&resource_path, settings)?;
```
Comment (linguofeng) [inline crates/tauri-bundler/src/bundle/windows/nsis/mod.rs:748]: ...

Comment (FabianLars) [reply crates/tauri-bundler/src/bundle/windows/nsis/mod.rs:748]: you already identified the code so are you open to creating a PR as well?
