### PR TITLE
fix: throw on custom protocol IPC fails

### LINKED ISSUE #14358: [bug] undefined is not an object (evaluating '[callbackId, data]')
### Describe the bug

We’re seeing the same error on iOS when requesting location permissions:
`undefined is not an object (evaluating '[callbackId, data]')`

It looks related to issue https://github.com/tauri-apps/tauri/issues/13907

It looks like the issue comes from the `then` following the `catch`.
Since the catch block doesn’t return anything, the then handler always receives undefined, which causes this error.

Relevant code:
https://github.com/tauri-apps/tauri/blob/67c7418c0677de6a7dd32fd3291301a2aef352ef/crates/tauri/scripts/ipc-protocol.js#L55-L67

### Reproduction

_No response_

### Expected behavior

_No response_

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 15.7.1 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.88.0 (6b00bc388 2025-06-23)
    ✔ cargo: 1.88.0 (873a06493 2025-05-10)
    ✔ rustup: 1.28.2 (e4f3ad6f8 2025-04-28)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 23.6.0
    - npm: 10.9.2

[-] Packages
    - tauri 🦀: 2.8.5, (outdated, latest: 2.9.1)
    - tauri-build 🦀: 2.4.1, (outdated, latest: 2.5.1)
    - wry 🦀: 0.53.3, (outdated, latest: 0.53.5)
    - tao 🦀: 0.34.3, (outdated, latest: 0.34.5)
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli : 2.7.1 (outdated, latest: 2.9.1)

[-] Plugins
    - tauri-plugin-os 🦀: 2.3.1
    - @tauri-apps/plugin-os : 2.3.0 (outdated, latest: 2.3.1)
    - tauri-plugin-log 🦀: 2.6.0, (outdated, latest: 2.7.0)
    - @tauri-apps/plugin-log : not installed!
    - tauri-plugin-geolocation 🦀: 2.3.0
    - @tauri-apps/plugin-geolocation : 2.3.0
    - tauri-plugin-haptics 🦀: 2.3.0
    - @tauri-apps/plugin-haptics : 2.3.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - framework: React
    - bundler: Rollup
```

### Stack trace

```text

```

### Additional context

We are going to update to the latest tauri versions, but in the code, the issue still exists, so we do not expect it to be solved

### PR DESCRIPTION
**Pull request by Legend-Master**
Fix #14358

A regression from #13325, `then` actually runs if the `catch` itself didn't throw

### CODE REVIEW

File: crates/tauri/scripts/ipc-protocol.js [hunk 1]
```diff
@@ -52,19 +52,21 @@
...
-          sendIpcMessage(message)
-        })
-        .then(([callbackId, data]) => {
-          window.__TAURI_INTERNALS__.runCallback(callbackId, data)
-        })
+        .then(
+          ([callbackId, data]) => {
+            window.__TAURI_INTERNALS__.runCallback(callbackId, data)
+          },
+          (e) => {
```
Comment (FabianLars) [inline crates/tauri/scripts/ipc-protocol.js:59]: TIL that .then has a second onRejected arg Oo

**Review by FabianLars — APPROVED** [review]
