### PR TITLE
fix(updater): fallback if tmp is on different mount point, closes #4500

### LINKED ISSUE #4500: [bug] Updater - Tauri API error: Invalid cross-device link (os error 18)
### Describe the bug

During the installUpdate() call, I receive the error "Tauri API error: Invalid cross-device link (os error 18)". I'm using a statically hosted update file following the [Update File JSON Format](https://tauri.app/v1/guides/distribution/updater/#update-file-json-format). I have the updater dialog set to false. I'm trying to update an AppImage.

I found another "Invalid cross-device link" [error](https://github.com/core-api/python-client/issues/176) in an unrelated python project.

### Reproduction

_No response_

### Expected behavior

_No response_

### Platform and versions

```shell
Environment
  › OS: Manjaro 21.3.1 X64
  › Node.js: 16.15.1
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../public
  › devPath: http://localhost:8080/
  › framework: Svelte
  › bundler: Rollup

App directory structure
  ├─ .git
  ├─ src-tauri
  ├─ public
  ├─ scripts
  ├─ .github
  ├─ .aws-sam
  ├─ src
  └─ node_modules
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lucasfernog**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

File: core/tauri/src/updater/core.rs [hunk 1]
```diff
@@ -640,14 +635,28 @@ impl<R: Runtime> Update<R> {
...
+  let mut tmp_dir_metadata = tmp_dir.path().metadata()?;
+
+  // fallback to cache_dir or CWD if the tmp directory is not in the same mount point
+  if extract_path_metadata.dev() != tmp_dir_metadata.dev() {
+    let fallback_dir =
+      dirs_next::cache_dir().unwrap_or_else(|| extract_path.parent().unwrap().to_path_buf());
+    tmp_dir = tempfile::Builder::new()
+      .prefix("tauri_current_app")
+      .tempdir_in(fallback_dir)?;
+    tmp_dir_metadata = tmp_dir.path().metadata()?
```
Comment (Beanow) [inline core/tauri/src/updater/core.rs]: It doesn't look like we're checking the metadata again to be sure those fallbacks are on the same mountpoint?
Especially if `~/.cache` is found and preferred over the current `.appimage` path, this seems quite possible.
I could be running the `appimage` from a network share with `~/.cache` on a local btrfs volume.

File: core/tauri/src/updater/core.rs [hunk 2]
```diff
@@ -661,21 +670,21 @@ fn copy_files_and_run<R: Read + Seek>(archive_buffer: R, extract_path: &Path) ->
...
-        return Err(crate::api::Error::Extract(err.to_string()));
+  extractor
+    .with_files(|entry| {
+      let path = entry.path()?;
+      if path.extension() == Some(OsStr::new("AppImage")) {
+        // if something went wrong during the extraction, we should restore previous app
+        if let Err(err) = entry.extract(extract_path) {
+          Move::from_source(tmp_app_image).to_dest(extract_path)?;
+          return Err(crate::api::Error::Extract(err.to_string()));
+        }
```
Comment (Beanow) [inline core/tauri/src/updater/core.rs]: Since you found a nice option to compare the mountpoints, the ultimate fallback imo should be to avoid move, and copy across the filesystem boundaries instead.

Comment (lucasfernog) [reply core/tauri/src/updater/core.rs]: well I didn't want to change the logic that much specially since it was audited already. I think if we fallback to the current appimage directory we're safe.

File: core/tauri/src/updater/core.rs (hunk 1 above)
Comment (lucasfernog) [reply core/tauri/src/updater/core.rs]: You're right. I'll see how I can change that.

File: core/tauri/src/updater/core.rs (hunk 2 above)
Comment (Beanow) [reply core/tauri/src/updater/core.rs]: That is, if none of the 3 dir options appear to be on the same mount point.

Comment (Beanow) [reply core/tauri/src/updater/core.rs]: > well I didn't want to change the logic that much specially since it was audited already. I think if we fallback to the current appimage directory we're safe.

Got it, sure that makes sense. Because I would _expect_ a sibling to the appimage to be the same file system.
Though we should still check that (previous comment).

File: core/tauri/src/updater/core.rs (hunk 1 above)
Comment (Beanow) [reply core/tauri/src/updater/core.rs]: A loop of candidates maybe :] And it should solve a second issue, namely right now the CWD won't be considered if `dirs_next::cache_dir()` is `Some`.

**Comment by lucasfernog** [comment]
I also removed the `#[cfg(feature = "updater")]`in the core.rs file since we do not have an specific feature for updater documentation generation anymore (we previously had one because the updater feature enabled the zip crate, which didn't cross compile for docs.rs - now fixed by removing its default features).

File: core/tauri/src/updater/core.rs (hunk 1 above)
Comment (lucasfernog) [reply core/tauri/src/updater/core.rs]: done @Beanow code might look weird with the vector of closures, but i think it's the way to remove duplicated code lol

File: core/tauri/src/updater/core.rs (hunk 2 above)
Comment (lucasfernog) [reply core/tauri/src/updater/core.rs]: Yeah I did that though it sounds unlikely that it would happen.

File: core/tauri/src/updater/core.rs (hunk 1 above)
Comment (Beanow) [reply core/tauri/src/updater/core.rs]: Yeah that looks like a good approach to me :ok_hand:

File: core/tauri/src/updater/core.rs (hunk 2 above)
Comment (Beanow) [reply core/tauri/src/updater/core.rs]: Current solution looks like a fair middle ground, trying three candidates to move or a clear error message :+1:

**Comment by Beanow** [comment]
I'll leave the call up to a maintainer, but my thoughts are addressed :ok_hand:

**Comment by lucasfernog** [comment]
Thanks for the review @Beanow
