### PR TITLE
fix: fire window-specific event on Window emit_to/emit_all, closes #4493

### LINKED ISSUE #4493: [bug] Differences in behavior between appWindow.listen() and listen()
### Describe the bug

`appWindow.listen()` isn't triggered by `window.emit_to` or `window.emit_all` calls, whereas `listen()` is. My conversation on Discord with @FabianLars suggested this wasn't supposed to the case.

### Reproduction

Given some JS code like:

```js
import { listen } from "@tauri-apps/api/event";
import { appWindow } from "@tauri-apps/api/window";

listen("foo", e => console.log("foo", e);
appWindow.listen("bar", e => console.log("bar", e));
```

and Rust like:

```rust
window.emit("foo", "payload"); // works
window.emit_to("main", "foo", "payload") // works
window.emit_all("foo", "payload") // works

window.emit("bar", "payload"); //works
window.emit_to("main", "bar", "payload") // does NOT work
window.emit_all("bar", "payload") // does NOT work
```

### Expected behavior

_No response_

### Platform and versions

```shell
❯ yarn tauri info                                                                                                                                                                
yarn run v1.22.17                                                                                                                                                                
$ /Users/isaac/code/lqbk/blot3/node_modules/.bin/tauri info                                                                                                                      
                                                                                                                                                                                 
Environment                                                                                                                                                                      
  › OS: Mac OS 12.4.0 X64                                                                                                                                                        
  › Node.js: 18.4.0                                                                                                                                                              
  › npm: 8.12.1                                                                                                                                                                  
  › pnpm: Not installed!                                                                                                                                                         
  › yarn: 1.22.17                                                                                                                                                                
  › rustup: 1.24.3                                                                                                                                                               
  › rustc: 1.61.0                                                                                                                                                                
  › cargo: 1.61.0                                                                                                                                                                
  › Rust toolchain: stable-aarch64-apple-darwin                                                                                                                                  
                                                                                                                                                                                 
Packages                                                                                                                                                                         
  › @tauri-apps/cli [NPM]: 1.0.0                                                                                                                                                 
  › @tauri-apps/api [NPM]: 1.0.1                                                                                                                                                 
  › tauri [RUST]: 1.0.0,                                                                                                                                                         
  › tauri-build [RUST]: 1.0.0,                                                                                                                                                   
  › tao [RUST]: 0.11.2,                                                                                                                                                          
  › wry [RUST]: 0.18.3,                                                                                                                                                          
                                                                                                                                                                                 
App                                                                                                                                                                              
  › build-type: bundle                                                                                                                                                           
  › CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: asset: customprotocol: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'                            
  › distDir: ../dist                                                                                                                                                             
  › devPath: http://localhost:3000/                                                                                                                                              
  › framework: React                                                                                                                                                             
                                                                                                                                                                                 
App directory structure                                                                                                                                                          
  ├─ types                                                                                                                                                                       
  ├─ test                                                                                                                                                                        
  ├─ dist                                                                                                                                                                        
  ├─ node_modules                                                                                                                                                                
  ├─ browser                                                                                                                                                                     
  ├─ public                                                                                                                                                                      
  ├─ src-tauri                                                                                                                                                                   
  └─ src                                                                                                                                                                         
✨  Done in 7.08s.  
```
```


### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lucasfernog**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

File: core/tauri/src/window.rs [hunk 1]
```diff
@@ -1339,6 +1356,7 @@ impl<R: Runtime> Window<R> {
     source_window_label: Option<&str>,
     payload: S,
   ) -> crate::Result<()> {
+    println!("emit internal {:?} {:?}", event, source_window_label);
```
Comment (amrbashir) [inline core/tauri/src/window.rs:1359]: seems like you forgot about this little dude

Comment (lucasfernog) [reply core/tauri/src/window.rs:1359]: just removed it, thanks
