### PR TITLE
fix(cli): apply `.taurignore` rules to workspace members, closes #5355

### LINKED ISSUE #5355: [bug] cargo workspace memebers can NOT be ignored by `.taurignore`
### Describe the bug

Hello, after making lots of changes on my tauri +yew code there is a weird thing about appeared few days ago.
Every time I change the code it close the app and open it again instead of just refresh? 
Now, I have no idea how to debug this because my code became really large.

### Reproduction

1. create monorepo multiple workspaces with cargo
2. change in file in a workspace

### Expected behavior

Just reload or refresh the app instead of closing it.

### Platform and versions

1.1.1

### Stack trace

```shell
.
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amrbashir**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

File: tooling/cli/src/interface/rust.rs [hunk 1]
```diff
@@ -364,27 +398,33 @@ impl Rust {
...
-      });
+      if !ignore_matcher.matched(path, true).is_ignore() {
+        info!("Watching {} for changes...", path.display());
+        lookup(path, |file_type, p| {
+          if p != path {
+            debug!("Watching {} for changes...", p.display());
+            let _ = watcher.watcher().watch(
+              &p,
+              if file_type.is_dir() {
+                RecursiveMode::Recursive
```
Comment (amrbashir) [inline tooling/cli/src/interface/rust.rs:442]: Since we are watching recursively, there maybe some files in this directory that are ignored and shouldn't trigger restart, so we need to use the `ignore_matcher` in the event loop to check if it is not ignored before triggering restart

Comment (lucasfernog) [reply tooling/cli/src/interface/rust.rs:442]: nice catch, pushed it

File: tooling/cli/src/interface/rust.rs [hunk 2]
```diff
@@ -255,6 +257,59 @@ impl Interface for Rust {
...
+        let _ = ignore_builder.add_line(None, &line);
+      }
+
+      matchers.push(ignore_builder.build().unwrap());
+    }
+  }
+
+  IgnoreMatcher(matchers)
+}
+
```
Comment (amrbashir) [inline tooling/cli/src/interface/rust.rs:312]: I am not sure why you need to store multiple ignore matcher, we just need to collect all `.taurignore` files in the common parent and add it to a single ignore matcher
```suggestion
fn build_ignore_matcher(dir: &Path) -> GitIgnore {
  let mut ignore_builder = GitignoreBuilder::new(path.parent().unwrap());

  // ignore crate doesn't expose an API to build `ignore::gitignore::GitIgnore`
  // with custom ignore file names so we have to walk the directory and collect
  // our custom ignore files and add it using `ignore::gitignore::GitIgnoreBuilder::add`
    for entry in ignore::WalkBuilder::new(dir)
      .require_git(false)
      .ignore(false)
      .overrides(
        ignore::overrides::OverrideBuilder::new(dir)
          .add(".taurignore")
          .unwrap()
          .build()
          .unwrap(),
      )
      .build()
      .flatten()
  {
    let path = entry.path();
    ignore_builder.add(path);

    if let Ok(ignore_file) = std::env::var("TAURI_DEV_WATCHER_IGNORE_FILE") {
      ignore_builder.add(dir.join(ignore_file));
    }

    for line in crate::dev::TAURI_DEV_WATCHER_GITIGNORE.lines().flatten() {
      let _ = ignore_builder.add_line(None, &line);
    }
  }

	ignore_builder
}

```

Comment (lucasfernog) [reply tooling/cli/src/interface/rust.rs:312]: well I tried that, but then relative paths doesn't work. For instance, if you have a workspace with the `lib/` and `src-tauri/` members, and a `lib/.taurignore` file ignoring `src/lib.rs` (which relatively to the common ancestor is `lib/src/lib.rs`), it only ignores properly if you use a dedicated `GitignoreBuilder::new(path)` where `path` points to the `lib/` folder.

Comment (lucasfernog) [reply tooling/cli/src/interface/rust.rs:312]: See [GitignoreBuilder::new](https://docs.rs/ignore/latest/ignore/gitignore/struct.GitignoreBuilder.html#method.new) for more info, particularly:
```
The path given should be the path at which the globs for this gitignore file should be matched. Note that paths are always matched relative to the root path given here. Generally, the root path should correspond to the directory containing a .gitignore file.
```

Comment (amrbashir) [reply tooling/cli/src/interface/rust.rs:312]: Ah, I think I only tested with `.taurignore` in the root. This is fine then.
