### PR TITLE
fix(cli.rs): pnpm tauri info exits with error (fix #2509)

### LINKED ISSUE #2509: pnpm tauri info exits with error code 101
### **Describe the bug**
Running `pnpm tauri info` exits with code 101

### **To Reproduce**
1. `pnpm init`
2. `pnpm add -D @tauri-apps/cli`
2. `pnpm add @tauri-apps/api`
3. `tauri init`
4. `pnpm tauri info`
5. Observe error

### **Expected behavior**
Display the correct versions and exit with no error. Also note that the incorrect version for `@tauri-apps/cli` is reported when using pnpm before my proposed fix.

### **Screenshots**
```sh
pnpm tauri info
Downloading Rust CLI...
Download Complete
 app:spawn Running "/home/barry/experiment/tauri/demo-1/node_modules/.pnpm/@tauri-apps+cli@1.0.0-beta.9/node_modules/@tauri-apps/cli/bin/tauri-cli tauri info" +0ms


Operating System - Ubuntu, version 20.04 X64

Node.js environment
  Node.js - 14.17.4
  @tauri-apps/cli - 1.0.0-beta.7 (outdated, latest: 1.0.0-beta.9)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected character 't' while parsing major version number")', src/info.rs:323:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  @tauri-apps/api - tauri-apps
 app:spawn Command "/home/barry/experiment/tauri/demo-1/node_modules/.pnpm/@tauri-apps+cli@1.0.0-beta.9/node_modules/@tauri-apps/cli/bin/tauri-cli" failed with exit code: 101 +0ms
```

### **Platform and Versions (required):**

```
Operating System - Ubuntu, version 20.04 X64

Node.js environment
  Node.js - 14.17.4
  @tauri-apps/cli - 1.0.0-beta.9
  @tauri-apps/api - 1.0.0-beta.6

Global packages
  npm - 7.20.3
  pnpm - 6.13.0
  yarn - 1.22.4

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/src-tauri
/node_modules

App
  tauri.rs - 1.0.0-beta.7
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - src-tauri/tauri.conf.json
  devPath - http://localhost:3000
```

### **Additional context**
My suggested fix produces the above output

### PR DESCRIPTION
**Pull request by linuxuser586**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

File: tooling/cli.rs/src/info.rs [hunk 1]
```diff
@@ -86,96 +93,141 @@ fn crate_latest_version(name: &str) -> Option<String> {
...
+        .arg(name)
+        .args(&["version", "--depth", "0"])
+        .current_dir(app_dir)
+        .output()?
     }
+    PackageManager::Pnpm => {
+      #[cfg(target_os = "windows")]
+      {
+        cmd = Command::new("cmd");
+        cmd.arg("/c").arg("npm");
```
Comment (amrbashir) [inline tooling/cli.rs/src/info.rs]:
```suggestion
        cmd.arg("/c").arg("pnpm");
```

File: tooling/cli.rs/src/info.rs [hunk 2]
```diff
@@ -576,3 +631,134 @@ impl Info {
...
+  if use_npm {
+    return Ok(PackageManager::Npm);
+  }
+
+  if use_pnpm {
+    return Ok(PackageManager::Pnpm);
+  }
+
+  Ok(PackageManager::Yarn)
+}
```
Comment (amrbashir) [inline tooling/cli.rs/src/info.rs]: It is better to change this to `if else`

**Review by amrbashir — CHANGES_REQUESTED** [review]
Thanks for your contribution, can you remove `vfs` dependency and use normal `std::fs` instead? seems to me it is not necessary to add `vfs`

File: tooling/cli.rs/src/info.rs [hunk 3]
```diff
@@ -576,3 +631,134 @@ impl Info {
...
+      "no lock file found, please first run your package manager install"
+    ));
+  }
+
+  if use_npm && (use_pnpm || use_yarn)
+    || use_pnpm && (use_npm || use_yarn)
+    || use_yarn && (use_npm || use_pnpm)
+  {
+    return Err(anyhow::anyhow!(
+      "only one package mangager should be used, but found npm {}, pnpm {}, yarn {}\nplease remove unused package manager lock files",
```
Comment (amrbashir) [inline tooling/cli.rs/src/info.rs]: can this also be changed to only mention found package managers, instead of  `found npm true, yarn false, pnpm true` it should be `found npm and pnpm`

File: tooling/cli.rs/src/info.rs (hunk 1 above)
Comment (linuxuser586) [reply tooling/cli.rs/src/info.rs]: Fixed

File: tooling/cli.rs/src/info.rs (hunk 2 above)
Comment (linuxuser586) [reply tooling/cli.rs/src/info.rs]: Fixed

File: tooling/cli.rs/src/info.rs (hunk 3 above)
Comment (linuxuser586) [reply tooling/cli.rs/src/info.rs]: Fixed

**Comment by linuxuser586** [comment]
@amrbashir I made the recommended changes. Please review.

File: tooling/cli.rs/src/info.rs [hunk 4]
```diff
@@ -360,9 +411,17 @@ impl Info {
...
-      .map(|dir| dir.join("yarn.lock").exists())
-      .unwrap_or_default();
+    let mut package_manager = PackageManager::Npm;
+    if let Some(app_dir) = &app_dir {
+      let file_names = read_dir(app_dir)
+        .unwrap()
+        .filter_map(|e| e.ok())
+        .filter(|e| e.metadata().unwrap().file_type().is_file())
+        .map(|e| e.file_name())
+        .map(|e| e.to_string_lossy().into_owned())
```
Comment (amrbashir) [inline tooling/cli.rs/src/info.rs]:
```suggestion
        .map(|e| e.file_name().to_string_lossy().into_owned())
```

File: tooling/cli.rs/src/info.rs [hunk 5]
```diff
@@ -360,9 +411,17 @@ impl Info {
...
     panic::set_hook(hook);
 
-    let use_yarn = app_dir
-      .map(|dir| dir.join("yarn.lock").exists())
-      .unwrap_or_default();
+    let mut package_manager = PackageManager::Npm;
+    if let Some(app_dir) = &app_dir {
+      let file_names = read_dir(app_dir)
+        .unwrap()
+        .filter_map(|e| e.ok())
```
Comment (amrbashir) [inline tooling/cli.rs/src/info.rs]:
```suggestion
        .filter(|e| e.ok())
```

**Review by amrbashir — APPROVED** [review]
Thanks again, The PR looks good to me but it might take a sometime to merge.

File: tooling/cli.rs/src/info.rs (hunk 4 above)
Comment (linuxuser586) [reply tooling/cli.rs/src/info.rs]: Fixed

File: tooling/cli.rs/src/info.rs (hunk 5 above)
Comment (linuxuser586) [reply tooling/cli.rs/src/info.rs]: Fixed

**Comment by linuxuser586** [comment]
@amrbashir I updated the code to default to npm when no lock files exists since that was the behavior before my change.

**Comment by amrbashir** [comment]
Nice, you basically read my mind.

**Review by lucasfernog — APPROVED** [review]

**Comment by chrisspiegl** [comment]
Is there a way to get the next branch working in a new project I am working on?

Or maybe release the current #next branch to the next version on NPM?

I am wondering cause it seems there are a lot of improvements since the latest beta release in august.

**Comment by FabianLars** [comment]
@chrisspiegl For the `next` cli you need to use the cargo based installation (`cargo install tauri-cli --git https://github.com/tauri` -> `cargo tauri dev`).

According to our release plans/guidelines, there won't be any next-only releases to npm and that wouldn't be enough anyway because the prebuilt clis (needed by the npm package) are pulled from a seperate github page.

**Comment by chrisspiegl** [comment]
Thank you for clearing that up. I will try the cargo based cli.

For anyone wondering, I had to fix the `cargo install` a little bit and it worked to install with:

`cargo install tauri-cli --git https://github.com/tauri-apps/tauri --branch next`

now I can run `cargo tauri info` as well as `cargo tauri dev` and it works as expected with the current state.
